<?php

namespace Database\Seeders;

use App\Models\Departure;
use App\Models\Destination;
use App\Models\ItineraryDay;
use App\Models\Tour;
use App\Models\TourCategory;
use App\Models\TourPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class TourSeeder extends Seeder
{
    /** Standard service list used on all itineraries. */
    private array $baseIncluded = [
        'English-speaking guide and experienced driver throughout',
        'Accommodation: family ger stays, tourist ger camps and expedition tents',
        'Entrance fees for protected areas and national parks',
        'Cultural shows and museum tickets as listed',
        'All meals on tour (B = breakfast, L = lunch, D = dinner)',
        'Drinking water every day',
        'Sleeping bag for countryside nights',
    ];

    private array $baseExcluded = [
        'International flights to and from Ulaanbaatar',
        'Travel and medical insurance (required)',
        'Alcoholic drinks',
        'Optional activities not listed in the itinerary',
        'Excess baggage fees',
        'Personal expenses and tips',
    ];

    private array $baseGoodToKnow = [
        ['title' => 'How we travel', 'body' => 'Countryside legs run in sturdy 4WD vehicles and Russian vans; several routes add horse or camel stages with local wranglers. Distances are real — treat the drives as part of the adventure.'],
        ['title' => 'Where you sleep', 'body' => 'A mix of family ger stays, tourist ger camps and expedition tents depending on the route. Budget and luxury camp upgrades can be arranged on most itineraries.'],
        ['title' => 'Group or private', 'body' => 'Scheduled group departures keep prices low; every route also runs privately on your own dates for 1–16 travelers, with the plan adjusted to your pace.'],
        ['title' => 'Weather & packing', 'body' => 'Mongolian weather swings hard between day and night in every season. Pack layers, sun protection and a windproof shell; we provide sleeping bags.'],
    ];

    /** slug => regex used to auto-attach destinations from itinerary text. */
    private array $destinationMatchers = [
        'khongor-sand-dunes' => '/khongor/i',
        'bayanzag-flaming-cliffs' => '/bayanzag|flaming/i',
        'yol-valley' => '/yol/i',
        'tsagaan-suvarga' => '/tsagaan suvarga/i',
        'ongi-monastery' => '/ongi/i',
        'baga-gazriin-chuluu' => '/baga gazriin/i',
        'terelj-national-park' => '/terelj|aryapala/i',
        'chingis-khan-statue' => '/statue|tsonjin/i',
        'khustai-national-park' => '/khustai/i',
        'khugnu-tarni' => '/khugnu|khogno/i',
        'kharkhorin-erdene-zuu' => '/kharkhorin|erdene zuu/i',
        'orkhon-valley' => '/orkhon|ulaantsutgalan|waterfall/i',
        'naiman-nuur' => '/eight lakes|naiman/i',
        'tsenkher-hot-springs' => '/tsenkher/i',
        'khorgo-terkh' => '/khorgo|terkh|white lake/i',
        'tuvkhun-temple' => '/tuvkhun/i',
        'ugii-lake' => '/ugii/i',
        'khuvsgul-lake' => '/khuvsgul/i',
        'darkhad-tsaatan' => '/tsaatan|darkhad|shine-?ider|murun/i',
        'amarbaysgalant' => '/amarbaysgalant/i',
        'uran-togoo' => '/uran togoo/i',
        'altai-tavan-bogd' => '/altai|tavan bogd|tsambagarav/i',
        'ulgii-eagle-hunters' => '/ulgii|eagle|ulaankhus|khovd/i',
        'great-lakes-west' => '/khyargas|telmen|uvs|achit|khar-?us|tolbo/i',
        'khentii-chinggis' => '/khentii|deluun|kherlen|baldan|khukh nuur|batnorov/i',
        'shiliin-bogd' => '/shiliin|ganga|taliin agui|moltsog/i',
        'ulaanbaatar' => '/ulaanbaatar/i',
    ];

    public function run(): void
    {
        $categoryIds = TourCategory::pluck('id', 'slug');
        $destinations = Destination::pluck('id', 'slug');

        foreach ($this->tours() as $i => $data) {
            $itinerary = $data['itinerary'];
            $departureRanges = $data['departures'] ?? [];
            $categorySlugs = $data['categories'];
            $base = $data['price_from'];
            unset($data['itinerary'], $data['departures'], $data['categories']);

            $tour = Tour::create($data + [
                'included' => $this->baseIncluded,
                'excluded' => $this->baseExcluded,
                'good_to_know' => $this->baseGoodToKnow,
                'sort_order' => $i,
            ]);

            $tour->categories()->attach(
                collect($categorySlugs)->map(fn ($slug) => $categoryIds[$slug])->filter()
            );

            // itinerary days + destination auto-attach
            $matchedDestinations = [];
            foreach ($itinerary as $n => $day) {
                ItineraryDay::create([
                    'tour_id' => $tour->id,
                    'day_number' => $n + 1,
                    'title' => $day[0],
                    'description' => $day[1],
                    'meals' => $day[2] ?? ($n === 0 ? 'L+D' : ($n === count($itinerary) - 1 ? 'B+L' : 'B+L+D')),
                    'accommodation' => $day[3] ?? ($n === count($itinerary) - 1 ? null : 'Ger camp / family ger'),
                    'distance' => $day[4] ?? null,
                ]);
                foreach ($this->destinationMatchers as $slug => $pattern) {
                    if (preg_match($pattern, $day[0].' '.$day[1])) {
                        $matchedDestinations[$slug] = true;
                    }
                }
            }
            $tour->destinations()->attach(
                collect(array_keys($matchedDestinations))
                    ->map(fn ($slug) => $destinations[$slug] ?? null)->filter()
            );

            // group-size price tiers derived from the group rate
            foreach ([[1, 2, 1.5], [3, 4, 1.25], [5, 8, 1.1], [9, 16, 1.0]] as [$min, $max, $factor]) {
                TourPrice::create([
                    'tour_id' => $tour->id,
                    'min_people' => $min,
                    'max_people' => $max,
                    'price' => round($base * $factor / 10) * 10,
                ]);
            }

            foreach ($departureRanges as [$start, $end]) {
                $seatsLeft = collect([4, 5, 6, 8, 10, 12])->random();
                Departure::create([
                    'tour_id' => $tour->id,
                    'start_date' => $start,
                    'end_date' => $end,
                    'price' => $base,
                    'seats_total' => 16,
                    'seats_left' => $seatsLeft,
                    'status' => $seatsLeft <= 6 ? 'guaranteed' : 'open',
                ]);
            }
        }
    }

    /** Shift a 2026 date range into 2027 keeping month/day. */
    private static function y27(string $start, string $end): array
    {
        return [
            Carbon::parse($start)->addYear()->toDateString(),
            Carbon::parse($end)->addYear()->toDateString(),
        ];
    }

    private function tours(): array
    {
        return [
            /* ── flagship join-in tours ─────────────────────────── */
            [
                'title' => 'The Nomadic Adventure Tour',
                'slug' => 'nomadic-adventure-tour',
                'excerpt' => 'Our flagship 21-day expedition through roughly 60% of Mongolia\'s greatest places — the whole Gobi, the Khangai heartland, the Darkhad taiga and Khuvsgul Lake in one unforgettable loop.',
                'overview' => "Three weeks, three Mongolias. The route opens in the Gobi with the painted cliffs of Tsagaan Suvarga, the ice gorge of Yol Valley, the singing Khongor dunes and the Flaming Cliffs of Bayanzag. It then climbs through the Orkhon valley — riding days, the Ulaantsutgalan waterfall, hot-spring evenings at Tsenkher — to the volcano country of Khorgo-Terkh.\n\nThe final act is the far north: over the passes to the Darkhad valley, two days as guests of the Tsaatan reindeer herders, then the blue immensity of Khuvsgul Lake before returning past Uran Togoo volcano and the great monastery of Amarbaysgalant. You sleep in family gers, tourist camps and expedition tents, and eat three honest meals a day the whole way.",
                'type' => 'join',
                'duration_days' => 21,
                'price_from' => 1680,
                'rating' => 5.0,
                'reviews_count' => 84,
                'image' => '/images/hero-steppe.svg',
                'highlights' => [
                    'Every icon of the Gobi, Khangai and the north in one route',
                    'Two days with the Tsaatan reindeer herders of the taiga',
                    'Horse riding in the Orkhon valley and at Khuvsgul Lake',
                    'Khorgo volcano, Tsenkher hot springs and Amarbaysgalant',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['adventure-overland', 'horse-riding', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'Drive south into the middle Gobi to the eroded clay cliffs of Tsagaan Suvarga, glowing white and orange at sunset.'],
                    ['Yol Valley', 'Hike the shaded gorge of Yol Valley in the Gurvan Saikhan mountains, where ice sheets survive deep into summer.'],
                    ['Khongor Sand Dunes', 'Cross to the great singing dunes — camel riding with a herder family and a sunset climb up the 200 m crest.'],
                    ['Bayanzag — Flaming Cliffs', 'Walk the red escarpment where the first dinosaur eggs were discovered, at its best in golden-hour light.'],
                    ['Ongi Monastery', 'Follow the desert steppe north to the riverside ruins of Ongi Monastery and camp beside the oasis.'],
                    ['Orkhon Valley', 'Enter the UNESCO-listed Orkhon valley and settle in with a horse-breeding family for the riding days ahead.'],
                    ['Ulaantsutgalan Waterfall', 'Ride and hike to the 20 m Ulaantsutgalan waterfall over the valley\'s ancient lava fields.'],
                    ['Tsenkher Hot Springs', 'A shorter travel day ending in the open-air thermal pools of Tsenkher under the larch forest.'],
                    ['Khorgo-Terkh National Park', 'Reach Terkhiin Tsagaan Nuur — the Great White Lake — beneath the Khorgo volcano.'],
                    ['Khorgo volcano day', 'Climb the crater rim, explore the lava caves and walk the lake shore; evening with a yak-herding family.'],
                    ['Shine-Ider village', 'Cross the Khangai passes to Shine-Ider, a classic herding village on the road north.'],
                    ['Murun', 'Resupply in Murun, the northern provincial capital, and continue toward the Darkhad depression.'],
                    ['Darkhad Valley', 'Over the pass into the Darkhad valley — big skies, bigger silence — to our partner family\'s camp.'],
                    ['Tsaatan camp', 'Ride into the taiga to the Tsaatan reindeer herders and sleep in an urts, their teepee-style dwelling.'],
                    ['Life with the reindeer', 'A full day in camp: milking, herding, and learning how the taiga provides for its people.'],
                    ['Back to the Darkhad', 'Return ride out of the forest and a farewell evening with our Darkhad hosts.'],
                    ['Khuvsgul Lake', 'Reach the western shore of Khuvsgul — the "Blue Pearl" — for a lakeside camp.'],
                    ['Khuvsgul free day', 'Kayak, ride the shoreline trails or simply do nothing beside the clearest water in the country.'],
                    ['Uran Togoo Volcano', 'Head south past larch ridges to the perfectly round crater of Uran Togoo.'],
                    ['Amarbaysgalant Monastery', 'Visit one of Mongolia\'s three great monastic centers, tucked in the quiet Iven valley.'],
                    ['Return to Ulaanbaatar', 'Roll back into the capital by late afternoon with three weeks of country behind you.'],
                ],
                'departures' => [
                    ['2026-05-22', '2026-06-11'],
                    ['2026-07-26', '2026-08-15'],
                    ['2026-08-02', '2026-08-22'],
                    self::y27('2026-05-22', '2026-06-11'),
                    self::y27('2026-08-02', '2026-08-22'),
                ],
            ],
            [
                'title' => 'The Mongol Discovery Tour',
                'slug' => 'mongol-discovery-tour',
                'excerpt' => 'Sixteen days linking the full Gobi circuit with the Khangai\'s hot springs and volcanoes and the deep blue of Khuvsgul Lake.',
                'overview' => "The Mongol Discovery is the classic south-to-north crossing: five days of Gobi icons, the old capital at Kharkhorin, hot-spring and volcano country in the Khangai, then three unhurried days at Khuvsgul Lake before returning via Uran Togoo volcano and Amarbaysgalant monastery.\n\nIt is the route we recommend to travelers who want the whole sweep of the country at a steadier pace than the 21-day expedition.",
                'type' => 'join',
                'duration_days' => 16,
                'price_from' => 1280,
                'rating' => 4.9,
                'reviews_count' => 112,
                'image' => '/images/lake-khuvsgul.svg',
                'highlights' => [
                    'The five Gobi icons, from Tsagaan Suvarga to Ongi',
                    'Kharkhorin and Erdene Zuu monastery',
                    'Khorgo volcano and Tsenkher hot springs',
                    'Three days on the shore of Khuvsgul Lake',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['discovery', 'adventure-overland', 'hiking-trekking', 'wildlife-photography'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'South to the painted clay cliffs of the middle Gobi for our first desert sunset.'],
                    ['Yol Valley', 'Gorge walk among ibex and bearded vultures in the Gurvan Saikhan range.'],
                    ['Khongor Sand Dunes', 'Camel trek along the dune edge and a sunset scramble up the singing crest.'],
                    ['Bayanzag — Flaming Cliffs', 'Dinosaur country: walk the red cliffs and the saxaul forest below.'],
                    ['Ongi Monastery', 'North to the Ongi river ruins; evening walk along the canyon rim.'],
                    ['Kharkhorin', 'The site of the imperial capital: Erdene Zuu monastery and the Kharkhorin museum.'],
                    ['Tsenkher Hot Springs', 'Soak away the desert dust in open-air thermal pools under the larches.'],
                    ['Khorgo-Terkh National Park', 'Over the passes to the Great White Lake and the Khorgo cinder cone.'],
                    ['Volcano day', 'Climb the crater rim, walk the lava fields and visit a herder family on the shore.'],
                    ['Shine-Ider village', 'A scenic mountain stage across the northern Khangai.'],
                    ['Khuvsgul Lake', 'Arrive on the western shore and settle into a lakeside ger camp.'],
                    ['Khuvsgul on the water', 'Boat or kayak day on the clearest big lake in Central Asia.'],
                    ['Khuvsgul on horseback', 'Ride the shoreline trails through larch forest; farewell bonfire with fresh fish.'],
                    ['Uran Togoo Volcano', 'South past Murun to the round crater of Uran Togoo.'],
                    ['Amarbaysgalant Monastery', 'Morning ceremony at the great monastery of the Iven valley.'],
                    ['Return to Ulaanbaatar', 'Back to the capital by late afternoon.'],
                ],
                'departures' => [
                    ['2026-06-12', '2026-06-27'],
                    ['2026-07-01', '2026-07-16'],
                    ['2026-08-02', '2026-08-17'],
                    self::y27('2026-06-12', '2026-06-27'),
                    self::y27('2026-07-01', '2026-07-16'),
                ],
            ],
            [
                'title' => 'The Horseback Adventure Tour',
                'slug' => 'horseback-adventure-tour',
                'excerpt' => 'Fourteen days built around a five-day ride to the Eight Lakes of Naiman Nuur, with the full Gobi circuit as the overture.',
                'overview' => "First the desert: Tsagaan Suvarga, Yol Valley, the Khongor dunes, the Flaming Cliffs and Ongi monastery. Then the saddle: five days riding from the Orkhon valley up into the volcanic highlands of Naiman Nuur — the Eight Lakes — with pack horses, local wranglers and camps by the water.\n\nThe route closes gently with Tsenkher hot springs and the semi-Gobi of Khugnu-Tarni. Confident beginners are welcome; the horses are steady and the wranglers are patient.",
                'type' => 'join',
                'duration_days' => 14,
                'price_from' => 960,
                'rating' => 4.9,
                'reviews_count' => 76,
                'image' => '/images/horse-trek.svg',
                'highlights' => [
                    'Five-day supported ride to the Eight Lakes',
                    'Full Gobi circuit before the saddle days',
                    'Nights with herder families in the Orkhon valley',
                    'Hot-spring recovery day at Tsenkher',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['horse-riding', 'adventure-overland', 'wildlife-photography'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'Into the Gobi: sunset at the painted cliffs of Tsagaan Suvarga.'],
                    ['Yol Valley', 'Hike the ice gorge of the Gurvan Saikhan mountains.'],
                    ['Khongor Sand Dunes', 'Camel ride at the singing dunes and a crest climb at dusk.'],
                    ['Bayanzag — Flaming Cliffs', 'Golden-hour walk through dinosaur country.'],
                    ['Ongi Monastery', 'North to the river ruins of Ongi.'],
                    ['Orkhon Valley', 'Meet the horses and wranglers; fitting, briefing and a first short ride.'],
                    ['Ride out', 'Leave the valley floor and climb toward the lava plateaus.', 'B+L+D', 'Expedition tent'],
                    ['Into the highlands', 'Long riding stage through larch fringe and open pasture.', 'B+L+D', 'Expedition tent'],
                    ['Naiman Nuur', 'Reach the first of the Eight Lakes and camp by the shore.', 'B+L+D', 'Expedition tent'],
                    ['Lakes day', 'Ride lake to lake through the volcanic basin — the best day in the saddle.', 'B+L+D', 'Expedition tent'],
                    ['Ride back', 'Descend to the Orkhon valley and a farewell evening with our host family.'],
                    ['Tsenkher Hot Springs', 'Trade the saddle for the thermal pools.'],
                    ['Khugnu-Tarni National Park', 'The semi-Gobi: dunes, granite hills and Erdene Khamba monastery.'],
                    ['Return to Ulaanbaatar', 'Back to the capital by late afternoon.'],
                ],
                'departures' => [
                    ['2026-04-28', '2026-05-07'],
                    ['2026-06-15', '2026-06-26'],
                    ['2026-07-01', '2026-07-12'],
                    self::y27('2026-06-15', '2026-06-26'),
                ],
            ],
            [
                'title' => 'The Tsaatan Tour',
                'slug' => 'tsaatan-tour',
                'excerpt' => 'Fifteen days to the reindeer people of the northern taiga — Amarbaysgalant, the Darkhad valley, two days in a Tsaatan camp and Khuvsgul Lake.',
                'overview' => "The Tsaatan are among the last reindeer-herding peoples on earth, moving camp through the taiga north-west of Khuvsgul. This route reaches them properly: north past Amarbaysgalant monastery and Uran Togoo volcano, into the Darkhad valley on horseback, and two full days living beside the herd in an urts.\n\nThe return south collects Khuvsgul Lake, the Khorgo-Terkh volcano country, Tsenkher hot springs and Erdene Zuu — a complete northern loop.",
                'type' => 'join',
                'duration_days' => 15,
                'price_from' => 1120,
                'rating' => 4.9,
                'reviews_count' => 58,
                'image' => '/images/winter-tour.svg',
                'highlights' => [
                    'Two days living with a Tsaatan reindeer family',
                    'Horseback stages through the Darkhad valley',
                    'Khuvsgul Lake and Khorgo volcano on the return',
                    'Amarbaysgalant monastery morning ceremony',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['horse-riding', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Amarbaysgalant Monastery', 'North to the Iven valley and the great monastery\'s evening quiet.'],
                    ['Uran Togoo Volcano', 'Walk into the round crater and camp beneath the birch forest.'],
                    ['Murun', 'Resupply in the northern capital and push toward the Darkhad.'],
                    ['Darkhad family', 'Over the pass to our Darkhad partner family; afternoon in the saddle.'],
                    ['Ride to the Tsaatan', 'Horseback into the taiga to the reindeer camp; first night in an urts.', 'B+L+D', 'Urts (tepee)'],
                    ['Life with the herd', 'Milking, herding and taiga craft — a full day inside Tsaatan daily life.', 'B+L+D', 'Urts (tepee)'],
                    ['Return to the Darkhad', 'Ride out of the forest and rest with our host family.'],
                    ['Khuvsgul Lake', 'Cross to the western shore of the Blue Pearl.'],
                    ['Khuvsgul day', 'Boat, ride or walk the shoreline; evening bonfire with fresh fish.'],
                    ['Shine-Ider village', 'South over the Khangai shoulder to Shine-Ider.'],
                    ['Khorgo-Terkh National Park', 'The Great White Lake beneath the Khorgo cinder cone.'],
                    ['Volcano day', 'Crater rim climb and lava-cave walk; yak-herder visit on the shore.'],
                    ['Tsenkher Hot Springs', 'Thermal-pool evening under the larches.'],
                    ['Khugnu-Tarni & Erdene Zuu', 'The semi-Gobi park and the great monastery at Kharkhorin.'],
                    ['Return to Ulaanbaatar', 'Home to the capital by late afternoon.'],
                ],
                'departures' => [
                    ['2026-08-05', '2026-08-19'],
                    self::y27('2026-08-05', '2026-08-19'),
                ],
            ],
            [
                'title' => 'The Gobi Mirage Tour',
                'slug' => 'gobi-mirage-tour',
                'excerpt' => 'Six fast days through the essential Gobi — painted cliffs, ice gorge, singing dunes, Flaming Cliffs and Ongi — closing in the semi-Gobi of Khugnu-Tarni.',
                'overview' => "The shortest way to see the real Gobi properly. One icon per day: Tsagaan Suvarga's painted cliffs, the Yol Valley gorge, camel riding at the Khongor dunes, the Flaming Cliffs at golden hour and the Ongi monastery ruins, finishing through the dunes and granite of Khugnu-Tarni on the way home.",
                'type' => 'join',
                'duration_days' => 6,
                'price_from' => 480,
                'rating' => 4.8,
                'reviews_count' => 134,
                'image' => '/images/gobi-dunes.svg',
                'highlights' => [
                    'All five southern icons in six days',
                    'Camel riding with a dune-side herder family',
                    'Flaming Cliffs at sunset',
                    'Scheduled group departures all summer',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['discovery', 'hiking-trekking', 'short-tours'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'Drive south to the painted clay cliffs for our first Gobi sunset.'],
                    ['Yol Valley', 'Hike the shaded ice gorge of the Gurvan Saikhan mountains.'],
                    ['Khongor Sand Dunes', 'Camel ride and a sunset climb up the singing crest.'],
                    ['Bayanzag & Ongi', 'The Flaming Cliffs by day and the Ongi monastery ruins by evening.'],
                    ['Khugnu-Tarni National Park', 'North to the semi-Gobi: dunes, granite hills and a nomad family visit.'],
                    ['Return to Ulaanbaatar', 'Back to the capital by mid-afternoon.'],
                ],
                'departures' => [
                    ['2026-05-15', '2026-05-20'],
                    ['2026-05-27', '2026-06-01'],
                    ['2026-06-05', '2026-06-10'],
                    ['2026-06-20', '2026-06-25'],
                    self::y27('2026-05-15', '2026-05-20'),
                    self::y27('2026-06-05', '2026-06-10'),
                    self::y27('2026-06-20', '2026-06-25'),
                ],
            ],
            [
                'title' => 'The Ice Festival Tour',
                'slug' => 'ice-festival-tour',
                'excerpt' => 'Six winter days to the Khuvsgul Ice Festival — ice sculptures, sleigh races and skating on a meter of blue ice, plus Amarbaysgalant and Uran Togoo.',
                'overview' => "Each winter Khuvsgul Lake freezes a meter thick and the lakeshore holds its Ice Festival: sculpture contests, horse-sleigh races, ice skating, wrestling in fur and long evenings by the stove. This compact route pairs two festival days with Amarbaysgalant monastery and Uran Togoo volcano under snow.\n\nDaytime temperatures run well below zero — we outfit every guest with expedition sleeping bags, and the gers stay warm all night.",
                'type' => 'join',
                'duration_days' => 6,
                'price_from' => 480,
                'rating' => 4.9,
                'reviews_count' => 41,
                'image' => '/images/winter-tour.svg',
                'highlights' => [
                    'Two full days at the Khuvsgul Ice Festival',
                    'Horse-sleigh rides on a frozen lake',
                    'Amarbaysgalant monastery in winter quiet',
                    'Small winter groups, warm gers',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'winter'],
                'itinerary' => [
                    ['Amarbaysgalant Monastery', 'North through the winter steppe to the great monastery of the Iven valley.'],
                    ['Murun', 'Cross the snowbound passes to the northern capital.'],
                    ['Ice Festival — day one', 'Opening ceremonies, ice sculptures and sleigh races on Khuvsgul\'s frozen shore.', 'B+L+D', 'Warm ger camp'],
                    ['Ice Festival — day two', 'Skating, ice games and evenings by the stove with local families.', 'B+L+D', 'Warm ger camp'],
                    ['Uran Togoo Volcano', 'South past the snow-cloaked crater of Uran Togoo.'],
                    ['Return to Ulaanbaatar', 'Back to the capital by evening.'],
                ],
                'departures' => [
                    ['2026-02-28', '2026-03-05'],
                    ['2026-03-04', '2026-03-09'],
                    self::y27('2026-02-28', '2026-03-05'),
                    self::y27('2026-03-04', '2026-03-09'),
                ],
            ],
            [
                'title' => 'The Mongolia Expedition Tour',
                'slug' => 'mongolia-expedition-tour',
                'excerpt' => 'Sixteen days from Khustai\'s wild horses across the Great Lakes to Altai Tavan Bogd and the Golden Eagle Festival, flying home from Khovd.',
                'overview' => "The long road west. From Khustai's takhi horses and the old capital at Kharkhorin, the route strings together the volcano country of Khorgo-Terkh and the vast lakes of the west — Telmen, Khyargas, Uvs, Achit — before climbing into the Altai for glaciers, Kazakh eagle-hunter homes and two festival days in Ulgii.\n\nA throat-singing evening in Khovd and a domestic flight home close one of the greatest overland journeys the country offers.",
                'type' => 'join',
                'duration_days' => 16,
                'price_from' => 1280,
                'rating' => 5.0,
                'reviews_count' => 39,
                'image' => '/images/altai-peaks.svg',
                'highlights' => [
                    'Golden Eagle Festival, both festival days',
                    'Altai Tavan Bogd glacier viewpoint',
                    'The Great Lakes chain of the west',
                    'Return flight from Khovd included',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['adventure-overland', 'festival-events', 'wildlife-photography'],
                'itinerary' => [
                    ['Khustai National Park', 'Evening drive among the wild takhi horses; first night in the semi-Gobi.'],
                    ['Kharkhorin', 'Erdene Zuu monastery and the imperial capital\'s museum.'],
                    ['Khorgo-Terkh National Park', 'To the Great White Lake beneath the Khorgo volcano.'],
                    ['Volcano day', 'Crater climb, lava caves and a lakeshore herder visit.'],
                    ['Telmen Lake', 'West across the passes to the salt-fringed Telmen basin.'],
                    ['Khyargas Lake', 'Long lake day through the Great Lakes depression.'],
                    ['Uvs Lake & Ulaangom', 'Mongolia\'s largest lake and the far-western provincial capital.'],
                    ['Achit & Uureg lakes', 'Border-country lakes beneath the first Altai snow peaks.'],
                    ['Ulgii & Ulaankhus', 'Into Kazakh Mongolia; evening with an eagle-hunting family.'],
                    ['Altai Tavan Bogd', 'Up the valley to the national park base beneath the five holy peaks.', 'B+L+D', 'Expedition tent'],
                    ['Glacier day', 'Hike to the Potanin glacier viewpoint facing Khuiten, the country\'s highest summit.', 'B+L+D', 'Expedition tent'],
                    ['Tsambagarav Mountain', 'Descend past the ice dome of Tsambagarav to the steppe.'],
                    ['Golden Eagle Festival — day one', 'Opening parade, eagle calling and horseback contests in Ulgii.'],
                    ['Golden Eagle Festival — day two', 'Finals day: the great chases, camel races and Kazakh games.'],
                    ['Khovd', 'South to Khovd for a throat-singing performance and farewell dinner.'],
                    ['Fly to Ulaanbaatar', 'Morning flight back across the country.', 'B', null],
                ],
                'departures' => [
                    ['2026-09-22', '2026-10-07'],
                    self::y27('2026-09-22', '2026-10-07'),
                ],
            ],

            /* ── private classics ───────────────────────────────── */
            [
                'title' => 'The Great Gobi Tour',
                'slug' => 'great-gobi-tour',
                'excerpt' => 'Seven private days across the full southern circuit, from Tsagaan Suvarga to Ongi, finishing in the semi-Gobi of Khugnu-Tarni.',
                'overview' => "The complete Gobi at private pace: painted cliffs, the Yol Valley gorge, camel days at the Khongor dunes, the Flaming Cliffs, Ongi monastery and the granite-and-dune country of Khugnu-Tarni on the road home. Your own vehicle, guide and cook — dates are yours to choose.",
                'type' => 'private',
                'duration_days' => 7,
                'price_from' => 560,
                'rating' => 4.8,
                'reviews_count' => 97,
                'image' => '/images/gobi-dunes.svg',
                'highlights' => [
                    'Full southern circuit in one week',
                    'Camel trek at the Khongor dunes',
                    'Yol Valley gorge hike',
                    'Private vehicle, guide and dates',
                ],
                'is_featured' => false,
                'is_best_seller' => true,
                'categories' => ['discovery', 'hiking-trekking', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'South to the painted cliffs of the middle Gobi.'],
                    ['Yol Valley', 'Gorge hike among ibex and lammergeiers.'],
                    ['Khongor Sand Dunes', 'Camel riding and the sunset crest climb.'],
                    ['Bayanzag — Flaming Cliffs', 'Dinosaur country in golden light.'],
                    ['Ongi Monastery', 'The river ruins and an evening on the canyon rim.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi dunes and the Erdene Khamba monastery.'],
                    ['Return to Ulaanbaatar', 'Back to the capital by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Silk Road Tour',
                'slug' => 'silk-road-tour',
                'excerpt' => 'Nine days on the old caravan line — Terelj, the Gobi icons, Erdene Zuu at Kharkhorin and the Khugnu Khan mountains.',
                'overview' => "A route that follows the logic of the caravans: out through Terelj's granite valleys, south across the Gobi's five icons, then north with the trade road to the monastery city of Kharkhorin and the Khugnu Khan mountains. History underfoot the whole way.",
                'type' => 'private',
                'duration_days' => 9,
                'price_from' => 720,
                'rating' => 4.8,
                'reviews_count' => 63,
                'image' => '/images/trans-mongolian.svg',
                'highlights' => [
                    'Terelj and the Gobi in one route',
                    'Erdene Zuu monastery at Kharkhorin',
                    'Camel stage at the Khongor dunes',
                    'Khugnu Khan mountain monasteries',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['discovery', 'hiking-trekking', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Terelj National Park', 'Granite valleys, Turtle Rock and the Aryapala temple hike.'],
                    ['Tsagaan Suvarga', 'The long road south to the painted cliffs.'],
                    ['Yol Valley', 'Ice-gorge hike in the Gurvan Saikhan range.'],
                    ['Khongor Sand Dunes', 'Camel day at the singing dunes.'],
                    ['Bayanzag — Flaming Cliffs', 'Golden-hour walk over dinosaur ground.'],
                    ['Ongi Monastery', 'North along the caravan line to the Ongi ruins.'],
                    ['Kharkhorin & Erdene Zuu', 'The imperial capital and Mongolia\'s oldest monastery.'],
                    ['Khogno Khan Mountains', 'Granite hills, hidden temples and a last nomad-family evening.'],
                    ['Return to Ulaanbaatar', 'Home by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Gobi Discovery Tour',
                'slug' => 'gobi-discovery-tour',
                'excerpt' => 'Eight days pairing Terelj\'s granite country with the full Gobi circuit — the ideal first look at Mongolia\'s south.',
                'overview' => "Terelj first, then the desert: this route opens in the granite valleys an hour from the capital before running the classic southern line — Tsagaan Suvarga, Yol Valley, the Khongor dunes, the Flaming Cliffs, Ongi — and returning through the Khogno Khan mountains.",
                'type' => 'private',
                'duration_days' => 8,
                'price_from' => 640,
                'rating' => 4.8,
                'reviews_count' => 71,
                'image' => '/images/gobi-dunes.svg',
                'highlights' => [
                    'Terelj plus the five Gobi icons',
                    'Camel riding at Khongor',
                    'Flaming Cliffs at sunset',
                    'Private dates year-round',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['discovery', 'hiking-trekking', 'short-tours'],
                'itinerary' => [
                    ['Terelj National Park', 'Turtle Rock, the Aryapala temple and a first family-ger night.'],
                    ['Tsagaan Suvarga', 'South to the painted cliffs.'],
                    ['Yol Valley', 'Hike the shaded gorge of the Three Beauties.'],
                    ['Khongor Sand Dunes', 'Camels by day, dune crest by sunset.'],
                    ['Bayanzag — Flaming Cliffs', 'The red escarpment of the dinosaur finds.'],
                    ['Ongi Monastery', 'Ruins, river and desert stars.'],
                    ['Khogno Khan Mountains', 'Semi-Gobi granite and a farewell nomad visit.'],
                    ['Return to Ulaanbaatar', 'Back by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Magnificent Mongolia Tour',
                'slug' => 'magnificent-mongolia-tour',
                'excerpt' => 'Our namesake 11-day route: the Gobi circuit plus the Orkhon valley\'s riding days, waterfall and hot springs.',
                'overview' => "The tour we named the company after. Five Gobi days flow into the green heart of the country: horse riding in the UNESCO-listed Orkhon valley, the Ulaantsutgalan waterfall, an evening in the Tsenkher hot springs and the semi-Gobi of Khugnu-Tarni to finish. Desert and heartland in ideal proportion.",
                'type' => 'private',
                'duration_days' => 11,
                'price_from' => 880,
                'rating' => 4.9,
                'reviews_count' => 88,
                'image' => '/images/hero-steppe.svg',
                'highlights' => [
                    'Gobi icons and the Orkhon valley in one route',
                    'Riding day with a horse-breeding family',
                    'Ulaantsutgalan waterfall',
                    'Tsenkher hot-spring evening',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['adventure-overland', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'First Gobi sunset at the painted cliffs.'],
                    ['Yol Valley', 'Ice-gorge hike among the vultures.'],
                    ['Khongor Sand Dunes', 'Camel trek and the singing crest.'],
                    ['Bayanzag — Flaming Cliffs', 'Golden hour over dinosaur ground.'],
                    ['Ongi Monastery', 'The river ruins of the middle Gobi.'],
                    ['Orkhon Valley', 'North into the UNESCO valley; settle in with our host family.'],
                    ['Riding day', 'A full day on horseback across the lava-field pastures.'],
                    ['Ulaantsutgalan Waterfall', 'Walk to the 20 m falls and along the basalt canyon.'],
                    ['Tsenkher Hot Springs', 'Thermal pools under the larch forest.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi dunes and granite on the road home.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'The Grand Naadam & Gobi Desert Tour',
                'slug' => 'grand-naadam-gobi-tour',
                'excerpt' => 'Naadam\'s opening day and the granite of Baga Gazriin Chuluu, then the full Gobi circuit — eight July days.',
                'overview' => "Timed each July to the National Naadam: the opening ceremony and first wrestling rounds, then straight into the desert — Baga Gazriin Chuluu's granite island, Tsagaan Suvarga, Yol Valley, the Khongor dunes, the Flaming Cliffs and Ongi, closing through Khugnu-Tarni. Festival color and desert silence in a single week.",
                'type' => 'private',
                'duration_days' => 8,
                'price_from' => 640,
                'rating' => 5.0,
                'reviews_count' => 52,
                'image' => '/images/naadam-festival.svg',
                'highlights' => [
                    'Naadam opening ceremony and wrestling',
                    'Baga Gazriin Chuluu granite island',
                    'The five Gobi icons',
                    'Fixed July departures, small groups',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Naadam & Baga Gazriin Chuluu', 'Morning at the Naadam opening ceremony, afternoon drive to the granite island of the middle Gobi.'],
                    ['Tsagaan Suvarga', 'The painted cliffs at sunset.'],
                    ['Yol Valley', 'Hike the ice gorge of the Three Beauties.'],
                    ['Khongor Sand Dunes', 'Camel riding and the crest climb.'],
                    ['Bayanzag — Flaming Cliffs', 'Dinosaur country in evening light.'],
                    ['Ongi Monastery', 'The river ruins and desert stars.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi granite and dunes.'],
                    ['Return to Ulaanbaatar', 'Back by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Divine Central Mongolia Tour',
                'slug' => 'divine-central-mongolia-tour',
                'excerpt' => 'Nine days deep in the Khangai — Kharkhorin, riding days by the Orkhon waterfalls, Tsenkher hot springs and the Khorgo volcano.',
                'overview' => "Central Mongolia at full depth: the monastery city of Kharkhorin, two riding days along the Orkhon river and its waterfalls, a hot-spring evening at Tsenkher and two days in the volcano country of Khorgo-Terkh before the semi-Gobi closes the loop.",
                'type' => 'private',
                'duration_days' => 9,
                'price_from' => 720,
                'rating' => 4.8,
                'reviews_count' => 66,
                'image' => '/images/volcano-terkh.svg',
                'highlights' => [
                    'Two riding days in the Orkhon valley',
                    'Khorgo crater and the Great White Lake',
                    'Erdene Zuu monastery',
                    'Tsenkher hot springs',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['horse-riding', 'sightseeing-cultural', 'hiking-trekking'],
                'itinerary' => [
                    ['To Kharkhorin', 'West to the imperial capital and Erdene Zuu monastery.'],
                    ['Orkhon Valley', 'Into the UNESCO valley to our horse-breeding host family.'],
                    ['Riding day', 'Full day in the saddle across the lava pastures.'],
                    ['Waterfall ride', 'Ride to the Ulaantsutgalan falls and picnic on the canyon rim.'],
                    ['Tsenkher Hot Springs', 'Larch-forest thermal pools.'],
                    ['Khorgo-Terkh National Park', 'To the Great White Lake beneath the volcano.'],
                    ['Volcano day', 'Crater climb, lava caves, lakeshore families.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi granite on the road home.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'The Blue Pearl Tour',
                'slug' => 'blue-pearl-tour',
                'excerpt' => 'Eleven northern days: Amarbaysgalant, Uran Togoo, three days on Khuvsgul Lake and the volcano country of Khorgo-Terkh.',
                'overview' => "A route built around water: three unhurried days on Khuvsgul — the Blue Pearl — framed by Amarbaysgalant monastery, the Uran Togoo crater, the Great White Lake at Khorgo-Terkh and a hot-spring evening at Tsenkher, closing past Erdene Zuu and the semi-Gobi.",
                'type' => 'private',
                'duration_days' => 11,
                'price_from' => 880,
                'rating' => 4.9,
                'reviews_count' => 54,
                'image' => '/images/lake-khuvsgul.svg',
                'highlights' => [
                    'Three full days at Khuvsgul Lake',
                    'Khorgo volcano and the Great White Lake',
                    'Amarbaysgalant monastery',
                    'Tsenkher hot springs',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['discovery', 'hiking-trekking', 'wildlife-photography'],
                'itinerary' => [
                    ['Amarbaysgalant Monastery', 'North to the great monastery of the Iven valley.'],
                    ['Uran Togoo Volcano', 'Walk into the round birch-lined crater.'],
                    ['Khuvsgul Lake', 'Arrive on the western shore of the Blue Pearl.'],
                    ['Khuvsgul on the water', 'Boat or kayak across the glass-clear shallows.'],
                    ['Khuvsgul on horseback', 'Ride the larch-forest shoreline trails.'],
                    ['Shine-Ider village', 'South across the Khangai shoulder.'],
                    ['Khorgo-Terkh National Park', 'The Great White Lake beneath the cinder cone.'],
                    ['Volcano day', 'Crater rim, lava caves and lakeshore herders.'],
                    ['Tsenkher Hot Springs', 'Thermal pools under the larches.'],
                    ['Erdene Zuu & Khugnu-Tarni', 'The great monastery and the semi-Gobi park.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'Dream Mongolia Tour',
                'slug' => 'dream-mongolia-tour',
                'excerpt' => 'Twelve days weaving the Gobi circuit into the Khangai\'s waterfalls, riding country, hot springs and volcanoes.',
                'overview' => "A generous middle path between our one-week Gobi routes and the full expeditions: all five southern icons, then the Ulaantsutgalan waterfall, a riding day in the Orkhon valley, Tsenkher's pools and two days at Khorgo-Terkh before the semi-Gobi finale.",
                'type' => 'private',
                'duration_days' => 12,
                'price_from' => 960,
                'rating' => 4.9,
                'reviews_count' => 47,
                'image' => '/images/volcano-terkh.svg',
                'highlights' => [
                    'Gobi and Khangai in balanced measure',
                    'Orkhon riding day and waterfall',
                    'Two days in volcano country',
                    'Hot springs at Tsenkher',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['adventure-overland', 'discovery'],
                'itinerary' => [
                    ['Tsagaan Suvarga', 'South to the painted cliffs.'],
                    ['Yol Valley', 'The ice gorge of the Three Beauties.'],
                    ['Khongor Sand Dunes', 'Camel day at the singing dunes.'],
                    ['Bayanzag — Flaming Cliffs', 'Golden hour over the red escarpment.'],
                    ['Ongi Monastery', 'River ruins and desert stars.'],
                    ['Ulaantsutgalan Waterfall', 'North to the Orkhon falls.'],
                    ['Orkhon riding day', 'Horseback across the UNESCO valley.'],
                    ['Tsenkher Hot Springs', 'Thermal pools under the larches.'],
                    ['Khorgo-Terkh National Park', 'The Great White Lake arrives.'],
                    ['Volcano day', 'Crater climb and lava caves.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi granite on the way home.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'West Mongolia Trails Tour',
                'slug' => 'west-mongolia-trails-tour',
                'excerpt' => 'Thirteen days from Khovd through the Great Lakes to Altai Tavan Bogd\'s glaciers, returning across the Khangai to Kharkhorin.',
                'overview' => "The west, end to end: Khar-Us and Tolbo lakes, eagle-hunter homes at Ulaankhus, trekking beneath the five holy peaks of Tavan Bogd, then the long beautiful road home by Khyargas and Telmen lakes, the Great White Lake, Tsenkher's springs and Erdene Zuu.",
                'type' => 'private',
                'duration_days' => 13,
                'price_from' => 1040,
                'rating' => 4.9,
                'reviews_count' => 33,
                'image' => '/images/altai-peaks.svg',
                'highlights' => [
                    'Trekking day in Altai Tavan Bogd',
                    'Eagle-hunter family at Ulaankhus',
                    'The Great Lakes chain',
                    'Khorgo volcano on the return',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['adventure-overland', 'hiking-trekking'],
                'itinerary' => [
                    ['Khovd & Khar-Us Lake', 'Fly west and drive to the reed-fringed Khar-Us Lake.'],
                    ['Tolbo Lake & Ulgii', 'Over the passes to Kazakh Mongolia.'],
                    ['Ulaankhus village', 'Evening with an eagle-hunting family.'],
                    ['Into the Altai', '4WD day up the border valleys.', 'B+L+D', 'Expedition tent'],
                    ['Tavan Bogd trek', 'Hike to the glacier viewpoint beneath the five holy peaks.', 'B+L+D', 'Expedition tent'],
                    ['Ulgii town', 'Bazaar, museum and a proper shower.'],
                    ['Khyargas Lake', 'East into the Great Lakes depression.'],
                    ['Telmen Lake', 'Long steppe stage to the salt-fringed basin.'],
                    ['Terkhiin Tsagaan Nuur', 'Arrive at the Great White Lake.'],
                    ['Khorgo hike', 'Crater rim and lava-field walking day.'],
                    ['Tsenkher Hot Springs', 'The Khangai\'s thermal pools.'],
                    ['Erdene Zuu & Khugnu-Tarni', 'Monastery morning and semi-Gobi afternoon.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'The Golden Eagle Festival Tour',
                'slug' => 'golden-eagle-festival-tour',
                'excerpt' => 'Eleven days to Ulgii\'s Golden Eagle Festival by way of Khustai, the volcano country and the Great Lakes, flying home from Khovd.',
                'overview' => "October in the far west: the parade of eagle hunters in full fur and embroidery, the calling contests, the mounted games. This route earns the festival overland — Khustai's wild horses, Kharkhorin, the Khorgo volcano and the Great Lakes chain — then spends a day with a hunting family in Ulaankhus before flying home.",
                'type' => 'private',
                'duration_days' => 11,
                'price_from' => 880,
                'rating' => 5.0,
                'reviews_count' => 45,
                'image' => '/images/eagle-hunter.svg',
                'highlights' => [
                    'Both days of the Golden Eagle Festival',
                    'A day in an eagle-hunter\'s home',
                    'Khustai, Kharkhorin and Khorgo en route',
                    'Domestic flight back from the west',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'wildlife-photography'],
                'itinerary' => [
                    ['Khustai & Kharkhorin', 'Takhi horses at dusk, then on to the old capital.'],
                    ['Khorgo-Terkh National Park', 'To the Great White Lake beneath the volcano.'],
                    ['Volcano day', 'Crater rim and lava caves.'],
                    ['Telmen Lake', 'West across the high passes.'],
                    ['Khyargas Lake', 'Through the Great Lakes depression.'],
                    ['Achit Lake & Ulgii', 'Border lakes and arrival in Kazakh Mongolia.'],
                    ['Eagle Festival — day one', 'Opening parade and the calling contests.'],
                    ['Eagle Festival — day two', 'Finals: the chases, kokpar and camel races.'],
                    ['Ulaankhus village', 'A day inside an eagle-hunting household.'],
                    ['Khovd', 'South for a throat-singing evening.'],
                    ['Fly to Ulaanbaatar', 'Morning flight home.', 'B', null],
                ],
            ],
            [
                'title' => 'Chingis Khan Tour',
                'slug' => 'chingis-khan-tour',
                'excerpt' => 'Ten days in the east — the Khan\'s birthplace at Deluun Boldog, Baldan Bereeven monastery, Shiliin Bogd and the Dariganga steppe.',
                'overview' => "The least-visited compass point, and the most storied: Khukh Nuur where Temujin was proclaimed khan, the restored temples of Baldan Bereeven, the birthplace monument at Deluun Boldog and the Kherlen river of his childhood. The route then swings south to sacred Shiliin Bogd, the Taliin Agui cave and Ganga Lake before closing at Terelj and the great equestrian statue.",
                'type' => 'private',
                'duration_days' => 10,
                'price_from' => 800,
                'rating' => 4.8,
                'reviews_count' => 29,
                'image' => '/images/hero-steppe.svg',
                'highlights' => [
                    'Deluun Boldog — the birthplace of Chinggis Khan',
                    'Baldan Bereeven monastery',
                    'Sacred Shiliin Bogd volcano at dawn',
                    'Ganga Lake and the Dariganga steppe',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['sightseeing-cultural', 'discovery'],
                'itinerary' => [
                    ['Khukh Nuur', 'East to the Blue Lake where the empire was proclaimed.'],
                    ['Baldan Bereeven Monastery', 'The restored mountain monastery of the Khentii.'],
                    ['Deluun Boldog', 'The birthplace monument and the sacred spring.'],
                    ['Kherlen River', 'Follow the river of the Khan\'s childhood across the steppe.'],
                    ['Shiliin Bogd & Taliin Agui', 'Climb the sacred volcano and explore the basalt cave.'],
                    ['Ganga Lake & Moltsog Els', 'Swan waters and the Dariganga dunes.'],
                    ['Nomad family day', 'A full day with an eastern herding family.'],
                    ['Terelj & the Statue', 'West to the 40 m equestrian statue and Terelj\'s granite.'],
                    ['Terelj morning', 'Aryapala temple hike and Turtle Rock.'],
                    ['Return to Ulaanbaatar', 'Back by midday.'],
                ],
            ],
            [
                'title' => 'Best of Central Mongolia Tour',
                'slug' => 'best-of-central-mongolia-tour',
                'excerpt' => 'Twelve days with four in the saddle to the Eight Lakes, plus Tuvkhun temple, Tsenkher springs and the Khorgo volcano.',
                'overview' => "The Khangai's greatest hits with a proper ride at the center: four horseback days from the Orkhon valley to the Eight Lakes of Naiman Nuur, book-ended by the waterfall, Zanabazar's mountaintop hermitage at Tuvkhun, Tsenkher's pools, two volcano days and the old capital.",
                'type' => 'private',
                'duration_days' => 12,
                'price_from' => 960,
                'rating' => 4.9,
                'reviews_count' => 38,
                'image' => '/images/khustai-horses.svg',
                'highlights' => [
                    'Four riding days to Naiman Nuur',
                    'Tuvkhun hermitage at 2,600 m',
                    'Khorgo volcano and the Great White Lake',
                    'Kharkhorin finale',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['horse-riding', 'hiking-trekking'],
                'itinerary' => [
                    ['Khugnu-Tarni National Park', 'The semi-Gobi opener: dunes and granite.'],
                    ['Orkhon Valley', 'Waterfall hike and horse briefing with our host family.'],
                    ['Ride out', 'First stage toward the volcanic highlands.', 'B+L+D', 'Expedition tent'],
                    ['High pastures', 'Climb through larch fringe to the plateau.', 'B+L+D', 'Expedition tent'],
                    ['Naiman Nuur', 'Reach the Eight Lakes and camp by the water.', 'B+L+D', 'Expedition tent'],
                    ['Ride back', 'Return stage to the Orkhon valley.'],
                    ['Tuvkhun Temple', 'Forest hike to Zanabazar\'s hermitage.'],
                    ['Tsenkher Hot Springs', 'Thermal-pool recovery evening.'],
                    ['Khorgo-Terkh National Park', 'To the Great White Lake.'],
                    ['Volcano day', 'Crater rim and lava caves.'],
                    ['Kharkhorin', 'Erdene Zuu monastery and the museum.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],
            [
                'title' => 'Scenic Central Mongolia Tour',
                'slug' => 'scenic-central-mongolia-tour',
                'excerpt' => 'Six easy days — Kharkhorin, an Orkhon riding day, Tsenkher hot springs and the semi-Gobi.',
                'overview' => "Central Mongolia's essentials at a comfortable pace: the monastery city, a day on horseback in the Orkhon valley, an evening in the Tsenkher pools and the dunes-and-granite of Khugnu-Tarni. A perfect first countryside route for families.",
                'type' => 'private',
                'duration_days' => 6,
                'price_from' => 480,
                'rating' => 4.8,
                'reviews_count' => 59,
                'image' => '/images/nomad-life.svg',
                'highlights' => [
                    'Erdene Zuu monastery',
                    'Orkhon valley riding day',
                    'Tsenkher hot springs',
                    'Gentle pacing, family friendly',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['discovery', 'short-tours', 'sightseeing-cultural'],
                'itinerary' => [
                    ['To Kharkhorin', 'West to the old capital and Erdene Zuu.'],
                    ['Orkhon Valley', 'Into the UNESCO valley to our host family.'],
                    ['Riding day', 'Horseback across the lava pastures.'],
                    ['Tsenkher Hot Springs', 'Larch-forest thermal pools.'],
                    ['Khugnu-Tarni National Park', 'Semi-Gobi granite and dunes.'],
                    ['Return to Ulaanbaatar', 'Back by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'Magical Khangai Region Tour',
                'slug' => 'magical-khangai-region-tour',
                'excerpt' => 'Eight days of the Khangai\'s water and fire — the waterfall, Tuvkhun temple, hot springs, the Great White Lake and Khorgo volcano.',
                'overview' => "A loop devoted to the mountain heart of the country: the Ulaantsutgalan falls, the forest hermitage of Tuvkhun, Tsenkher's open-air pools, then the volcanic pair of the Great White Lake and the Khorgo crater, closing through Kharkhorin.",
                'type' => 'private',
                'duration_days' => 8,
                'price_from' => 640,
                'rating' => 4.8,
                'reviews_count' => 42,
                'image' => '/images/volcano-terkh.svg',
                'highlights' => [
                    'Ulaantsutgalan waterfall',
                    'Tuvkhun forest hermitage',
                    'Khorgo crater climb',
                    'Tsenkher hot springs',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['hiking-trekking', 'discovery'],
                'itinerary' => [
                    ['Khugnu-Tarni National Park', 'Semi-Gobi start among dunes and granite.'],
                    ['Ulaantsutgalan Waterfall', 'To the Orkhon falls and the basalt canyon.'],
                    ['Tuvkhun Temple', 'Forest hike to the mountaintop hermitage.'],
                    ['Tsenkher Hot Springs', 'Thermal pools under the larches.'],
                    ['Great White Lake', 'Arrive at Terkhiin Tsagaan Nuur.'],
                    ['Khorgo volcano', 'Crater rim climb and lava caves.'],
                    ['Kharkhorin', 'Erdene Zuu monastery on the road home.'],
                    ['Return to Ulaanbaatar', 'Back by late afternoon.'],
                ],
            ],

            /* ── festivals & winter ─────────────────────────────── */
            [
                'title' => 'The Yak Festival Tour',
                'slug' => 'yak-festival-tour',
                'excerpt' => 'Seven July days around the Yak Festival in Bat-Ulzii — races, yak polo and rodeo — woven into the best of the Khangai.',
                'overview' => "Every summer the herders of Bat-Ulzii in Ovorkhangai hold their Yak Festival: races, yak polo, rodeo riding and a very serious beauty contest for the shaggiest competitors. We build the festival into a week of Ugii Lake, Tsenkher springs, Tuvkhun temple, Orkhon riding and Erdene Zuu.",
                'type' => 'private',
                'duration_days' => 7,
                'price_from' => 560,
                'rating' => 4.9,
                'reviews_count' => 31,
                'image' => '/images/nomad-life.svg',
                'highlights' => [
                    'Yak races, polo and rodeo at the festival',
                    'Ugii Lake birdlife',
                    'Tuvkhun temple and the Orkhon falls',
                    'Erdene Zuu on the road home',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Ugii Lake', 'West to the warm steppe lake and its cranes.'],
                    ['Tsenkher Hot Springs', 'Thermal pools under the larches.'],
                    ['Tuvkhun & Orkhon Valley', 'Hermitage hike, then down to the great valley.'],
                    ['Riding & waterfalls', 'Horseback day to the Ulaantsutgalan falls.'],
                    ['Yak Festival', 'Races, polo, rodeo and the beauty contest at Bat-Ulzii.'],
                    ['Khugnu-Tarni & Erdene Zuu', 'Monastery morning and semi-Gobi afternoon.'],
                    ['Return to Ulaanbaatar', 'Back by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Camel Festival Tour',
                'slug' => 'camel-festival-tour',
                'excerpt' => 'Seven March days in the winter Gobi for the Thousand Camel Festival — races, polo and herder culture among the dunes.',
                'overview' => "March in the Gobi means the Camel Festival: races across the frozen steppe, camel polo, processions in full winter dress and long evenings with herding families. The route wraps the festival in the winter faces of Bayanzag, the Khongor dunes, Yol valley and Tsagaan Suvarga.",
                'type' => 'private',
                'duration_days' => 7,
                'price_from' => 560,
                'rating' => 4.8,
                'reviews_count' => 26,
                'image' => '/images/gobi-dunes.svg',
                'highlights' => [
                    'Camel races and polo at the festival',
                    'The Gobi icons in winter light',
                    'Nights with camel-herding families',
                    'Far fewer travelers than summer',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'winter', 'wildlife-photography'],
                'itinerary' => [
                    ['Nomad family', 'South to a camel-herding household of the middle Gobi.'],
                    ['Bayanzag — Flaming Cliffs', 'The red escarpment under winter light.'],
                    ['Camel Festival', 'Race day: camel racing, polo and the winter procession.'],
                    ['Khongor Sand Dunes', 'Hike the crest and ride camels along the dune edge.'],
                    ['Yol Valley', 'The gorge at its iciest and most beautiful.'],
                    ['Tsagaan Suvarga', 'Painted cliffs on the road north.'],
                    ['Return to Ulaanbaatar', 'Back by evening.'],
                ],
            ],
            [
                'title' => 'The Winter Horse Festival Tour',
                'slug' => 'winter-horse-festival-tour',
                'excerpt' => 'Five days to Khentii\'s Winter Horse Festival — herds in frost, horsemanship games and deel-clad riders — plus Terelj and the great statue.',
                'overview' => "In deep winter the herders of Batnorov in Khentii province gather their horses for a festival of horsemanship: lassoing, races and processions of riders in embroidered winter deels — one of the best photography events in the country. Terelj's snowbound granite and the Chinggis statue close the route.",
                'type' => 'private',
                'duration_days' => 5,
                'price_from' => 400,
                'rating' => 4.9,
                'reviews_count' => 22,
                'image' => '/images/winter-tour.svg',
                'highlights' => [
                    'Two days at the Winter Horse Festival',
                    'Herds steaming in the frost — a photographer\'s dream',
                    'Terelj National Park under snow',
                    'The 40 m Chinggis Khan statue',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'winter', 'wildlife-photography'],
                'itinerary' => [
                    ['To Batnorov, Khentii', 'East across the winter steppe to the festival grounds.'],
                    ['Festival — day one', 'Races, lasso contests and the parade of winter deels.'],
                    ['Festival — day two', 'Horsemanship finals and evenings with herding families.'],
                    ['Statue & Terelj', 'West to the equestrian statue and into snowbound Terelj.'],
                    ['Aryapala & return', 'Temple hike, then back to Ulaanbaatar.'],
                ],
            ],
            [
                'title' => 'The Spring Eagle Festival Tour',
                'slug' => 'spring-eagle-festival-tour',
                'excerpt' => 'A two-day March escape to the Spring Eagle Festival near Ulaanbaatar — hunters, eagles and mounted games without the trip west.',
                'overview' => "Each early March the eagle hunters bring their birds east for a spring festival at Chingisiin Khuree, an hour from the capital: the parade, the calling contests and hunting demonstrations at full gallop. The ideal festival taste for travelers who cannot reach Ulgii in October.",
                'type' => 'private',
                'duration_days' => 2,
                'price_from' => 160,
                'rating' => 4.7,
                'reviews_count' => 35,
                'image' => '/images/eagle-hunter.svg',
                'highlights' => [
                    'Eagle hunters an hour from the capital',
                    'Calling contests and mounted demonstrations',
                    'Winter-steppe photography',
                    'Weekend-sized itinerary',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'winter', 'short-tours'],
                'itinerary' => [
                    ['Festival day', 'Opening parade, eagle-calling contests and hunting demonstrations at Chingisiin Khuree.'],
                    ['Festival & return', 'Morning finals, lunch with the hunters, back to the city by evening.'],
                ],
            ],
            [
                'title' => 'The Lunar New Year Tour',
                'slug' => 'lunar-new-year-tour',
                'excerpt' => 'Celebrate Tsagaan Sar with a herding family in Khugnu-Tarni — two days of greetings, buuz and winter riding.',
                'overview' => "Tsagaan Sar — the lunar new year — is Mongolia's warmest tradition in its coldest month: the eldest greeted at dawn, a mountain of buuz, and every guest welcomed like family. We celebrate it where it means most, in a herder's ger in Khugnu-Tarni, with camel and horse rides between the feasting.",
                'type' => 'private',
                'duration_days' => 2,
                'price_from' => 160,
                'rating' => 4.9,
                'reviews_count' => 19,
                'image' => '/images/winter-tour.svg',
                'highlights' => [
                    'Tsagaan Sar morning with a host family',
                    'Traditional greetings and the buuz feast',
                    'Winter camel and horse riding',
                    'February departure, timed to the lunar calendar',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['festival-events', 'winter', 'sightseeing-cultural', 'short-tours'],
                'itinerary' => [
                    ['Khugnu-Tarni National Park', 'Join our host family on New Year\'s Eve for the bituun feast.'],
                    ['Tsagaan Sar & return', 'Dawn greetings, buuz and khadag exchanges, then back to the city.'],
                ],
            ],

            /* ── short tours ────────────────────────────────────── */
            [
                'title' => 'Once in Mongolia Tour',
                'slug' => 'once-in-mongolia-tour',
                'excerpt' => 'Three days, three worlds: wild horses at Khustai, Erdene Zuu at Kharkhorin and the semi-Gobi of Khugnu-Tarni.',
                'overview' => "The best possible use of three days: an evening among Khustai's reintroduced takhi — the world's only true wild horse — the great monastery at Kharkhorin, and a night with a herding family among the dunes and granite of Khugnu-Tarni, with camel and horse riding before the drive home.",
                'type' => 'private',
                'duration_days' => 3,
                'price_from' => 240,
                'rating' => 4.8,
                'reviews_count' => 92,
                'image' => '/images/khustai-horses.svg',
                'highlights' => [
                    'Takhi wild horses at dusk',
                    'Erdene Zuu monastery',
                    'Semi-Gobi family stay',
                    'Ideal between flights',
                ],
                'is_featured' => false,
                'is_best_seller' => true,
                'categories' => ['short-tours', 'wildlife-photography', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Khustai & Kharkhorin', 'Wild-horse evening drive, then west to the old capital.'],
                    ['Khugnu-Tarni National Park', 'Erdene Zuu in the morning; dunes, granite and a family ger by night.'],
                    ['Return to Ulaanbaatar', 'Camel ride at dawn, back to the city by afternoon.'],
                ],
            ],
            [
                'title' => 'The Mongolia Express Tour',
                'slug' => 'mongolia-express-tour',
                'excerpt' => 'Three days pairing the semi-Gobi\'s nomad life with Terelj\'s granite and the great equestrian statue.',
                'overview' => "A fast, complete taste of the countryside: a herder-family night in Khugnu-Tarni, Terelj's Turtle Rock and Aryapala temple, and the 40 m Chinggis Khan statue on the way home. Runs year-round, including the deep winter months.",
                'type' => 'private',
                'duration_days' => 3,
                'price_from' => 240,
                'rating' => 4.7,
                'reviews_count' => 64,
                'image' => '/images/terelj-park.svg',
                'highlights' => [
                    'Nomad family night in the semi-Gobi',
                    'Terelj and Aryapala temple',
                    'Chinggis Khan statue',
                    'Runs in every season',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['short-tours', 'winter', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Khugnu-Tarni National Park', 'West to the semi-Gobi for dunes, granite and a family ger night.'],
                    ['Terelj National Park', 'Turtle Rock, the Aryapala hike and a ger-camp evening.'],
                    ['Statue & return', 'Climb the great statue, then back to the city.'],
                ],
            ],
            [
                'title' => 'The Nomads Tour',
                'slug' => 'nomads-tour',
                'excerpt' => 'Four days across Terelj, the semi-Gobi and Kharkhorin — the compact heartland circuit.',
                'overview' => "Terelj's granite valleys, a night with herders in Khugnu-Tarni and the monastery city of Kharkhorin, joined into one relaxed half-week loop. The route most travelers with four spare days should take.",
                'type' => 'private',
                'duration_days' => 4,
                'price_from' => 320,
                'rating' => 4.8,
                'reviews_count' => 48,
                'image' => '/images/nomad-life.svg',
                'highlights' => [
                    'Terelj granite and temple hike',
                    'Herder family night',
                    'Erdene Zuu monastery',
                    'Gentle distances every day',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['short-tours', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Terelj National Park', 'Granite valleys, Turtle Rock and Aryapala temple.'],
                    ['Khugnu-Tarni National Park', 'West to the semi-Gobi and our host family.'],
                    ['Kharkhorin', 'Erdene Zuu monastery and the imperial-capital museum.'],
                    ['Return to Ulaanbaatar', 'Back by mid-afternoon.'],
                ],
            ],
            [
                'title' => 'The Terelj National Park Tour',
                'slug' => 'terelj-national-park-tour',
                'excerpt' => 'Two days in Terelj — the great statue, horse riding among the granite, a ger-camp night and the Aryapala temple hike.',
                'overview' => "The classic overnight escape, available in every season: climb the Chinggis Khan statue, ride among Terelj's granite towers, sleep in a ger camp and hike to the Aryapala meditation temple before an easy return to the city.",
                'type' => 'private',
                'duration_days' => 2,
                'price_from' => 160,
                'rating' => 4.7,
                'reviews_count' => 118,
                'image' => '/images/terelj-park.svg',
                'highlights' => [
                    'Chinggis Khan statue',
                    'Horse riding in the park',
                    'Ger camp night',
                    'Aryapala temple hike',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['short-tours', 'horse-riding'],
                'itinerary' => [
                    ['Statue & Terelj', 'The 40 m equestrian statue, lunch, then an afternoon ride among the granite.'],
                    ['Aryapala & return', 'Morning hike to the meditation temple; back to the city after lunch.'],
                ],
            ],
            [
                'title' => 'Amarbaysgalant Monastery Tour',
                'slug' => 'amarbaysgalant-monastery-tour',
                'excerpt' => 'An overnight run north to one of Mongolia\'s three great monasteries, serene in the Iven valley.',
                'overview' => "Amarbaysgalant is the most architecturally complete of Mongolia's great monasteries, and among the quietest. This overnight route reaches it with time for the evening light, the morning ceremony and the hilltop stupas above the valley.",
                'type' => 'private',
                'duration_days' => 2,
                'price_from' => 160,
                'rating' => 4.8,
                'reviews_count' => 27,
                'image' => '/images/kharkhorin.svg',
                'highlights' => [
                    'Evening and morning at the monastery',
                    'Hilltop stupa walk',
                    'Iven valley scenery',
                    'Easy overnight from the capital',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['short-tours', 'sightseeing-cultural'],
                'itinerary' => [
                    ['To Amarbaysgalant', 'North through the Selenge steppe; evening light on the temple roofs.'],
                    ['Ceremony & return', 'Morning chanting, the stupa hill, then back to the city.'],
                ],
            ],
            [
                'title' => 'The UB City Tour',
                'slug' => 'ub-city-tour',
                'excerpt' => 'One full day in the capital — Gandan monastery, the National Museum, Sukhbaatar Square, Zaisan Hill and a folk performance.',
                'overview' => "Ulaanbaatar rewards a real day: morning chanting at Gandan monastery, the National Museum's sweep from deer stones to democracy, lunch downtown, the Bogd Khan winter palace, sunset from Zaisan Hill and an evening of throat singing and contortion. Cashmere stops on request.",
                'type' => 'private',
                'duration_days' => 1,
                'price_from' => 80,
                'rating' => 4.7,
                'reviews_count' => 86,
                'image' => '/images/ulaanbaatar.svg',
                'highlights' => [
                    'Gandan monastery morning chanting',
                    'National Museum of Mongolia',
                    'Zaisan Hill viewpoint',
                    'Evening folk performance',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['short-tours', 'sightseeing-cultural'],
                'itinerary' => [
                    ['Ulaanbaatar in a day', 'Gandan, the National Museum, Sukhbaatar Square, the Bogd Khan palace, Zaisan sunset and a folk show.', 'L', null],
                ],
            ],
            [
                'title' => 'Horse Riding in Khugnu-Tarni Tour',
                'slug' => 'horse-riding-khugnu-tarni-tour',
                'excerpt' => 'Three days of riding in the semi-Gobi — dunes, granite hills and herder hospitality, sized for beginners.',
                'overview' => "Khugnu-Tarni is the perfect riding classroom: open going, gentle horses and scenery that swings from dunes to granite peaks within a single ride. A full middle day in the saddle, based from our partner family's camp.",
                'type' => 'private',
                'duration_days' => 3,
                'price_from' => 240,
                'rating' => 4.8,
                'reviews_count' => 44,
                'image' => '/images/horse-trek.svg',
                'highlights' => [
                    'Full riding day in the semi-Gobi',
                    'Beginner-friendly horses and wranglers',
                    'Family ger nights',
                    'Dunes and granite in one park',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['horse-riding', 'short-tours'],
                'itinerary' => [
                    ['To Khugnu-Tarni', 'West to the park; fitting, briefing and a first evening ride.'],
                    ['Riding day', 'Dunes to granite and back — a full day in the saddle.'],
                    ['Return to Ulaanbaatar', 'Morning ride, lunch with the family, home by afternoon.'],
                ],
            ],
        ];
    }
}
