<?php

namespace Database\Seeders;

use App\Models\Departure;
use App\Models\Destination;
use App\Models\ItineraryDay;
use App\Models\Tour;
use App\Models\TourCategory;
use App\Models\TourPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class TourSeeder extends Seeder
{
    private array $baseIncluded = [
        'Accommodation as listed (hotel in Ulaanbaatar, ger camps in the countryside)',
        'Private 4WD vehicle with experienced driver and all fuel',
        'Professional English-speaking guide throughout',
        'All meals as listed (B = breakfast, L = lunch, D = dinner)',
        'National park entrance fees and protected-area permits',
        'Bottled drinking water every day',
        'Airport transfers on arrival and departure',
    ];

    private array $baseExcluded = [
        'International flights to and from Ulaanbaatar',
        'Travel insurance (required for all travelers)',
        'Personal expenses, laundry and drinks',
        'Optional activities not listed in the itinerary',
        'Photo and video fees at museums and monasteries',
        'Single supplement for solo travelers',
        'Tips for guide and driver (at your discretion)',
    ];

    private array $baseGoodToKnow = [
        ['title' => 'Fitness level', 'body' => 'This trip suits any traveler in ordinary good health. Countryside drives can be long and roads are often unpaved — think of the drive itself as part of the adventure.'],
        ['title' => 'Ger camp facilities', 'body' => 'Tourist ger camps provide real beds, wood stoves, shared western bathrooms and hot showers. Electricity is usually available in the evenings for charging.'],
        ['title' => 'Weather', 'body' => 'Mongolian weather changes fast. Even in summer, evenings can drop below 10°C, so pack layers, a warm fleece and a windproof jacket.'],
        ['title' => 'Money', 'body' => 'Bring some cash in USD to exchange. ATMs are plentiful in Ulaanbaatar but rare in the countryside; small purchases are in Mongolian tugrik.'],
    ];

    public function run(): void
    {
        foreach ($this->tours() as $i => $data) {
            $itinerary = $data['itinerary'];
            $prices = $data['prices'] ?? [];
            $departureDates = $data['departures'] ?? [];
            $categorySlugs = $data['categories'];
            $destinationSlugs = $data['destinations'];
            unset($data['itinerary'], $data['prices'], $data['departures'], $data['categories'], $data['destinations']);

            $tour = Tour::create($data + [
                'included' => $data['included'] ?? $this->baseIncluded,
                'excluded' => $data['excluded'] ?? $this->baseExcluded,
                'good_to_know' => $this->baseGoodToKnow,
                'sort_order' => $i,
            ]);

            $tour->categories()->attach(
                TourCategory::whereIn('slug', $categorySlugs)->pluck('id')
            );
            $tour->destinations()->attach(
                Destination::whereIn('slug', $destinationSlugs)->pluck('id')
            );

            foreach ($itinerary as $n => $day) {
                ItineraryDay::create([
                    'tour_id' => $tour->id,
                    'day_number' => $n + 1,
                    'title' => $day[0],
                    'description' => $day[1],
                    'meals' => $day[2] ?? 'B+L+D',
                    'accommodation' => $day[3] ?? 'Ger camp',
                    'distance' => $day[4] ?? null,
                ]);
            }

            foreach ($prices as $tier) {
                TourPrice::create([
                    'tour_id' => $tour->id,
                    'min_people' => $tier[0],
                    'max_people' => $tier[1],
                    'price' => $tier[2],
                ]);
            }

            foreach ($departureDates as $start) {
                $startDate = Carbon::parse($start);
                $seatsLeft = collect([4, 6, 9, 12, 16])->random();
                Departure::create([
                    'tour_id' => $tour->id,
                    'start_date' => $startDate->toDateString(),
                    'end_date' => $startDate->copy()->addDays($tour->duration_days - 1)->toDateString(),
                    'price' => $tour->price_from,
                    'seats_total' => 16,
                    'seats_left' => $seatsLeft,
                    'status' => $seatsLeft <= 6 ? 'guaranteed' : 'open',
                ]);
            }
        }
    }

    private function tours(): array
    {
        return [
            [
                'title' => 'Grand Mongolia Tour',
                'slug' => 'grand-mongolia-tour',
                'excerpt' => 'Our flagship two-week journey across the Gobi Desert and Central Mongolia — dunes, monasteries, wild horses and nights with nomadic families.',
                'overview' => "This is the journey we have refined for over twenty years: a complete loop through Mongolia's south and heartland. You will watch sunset from the singing dunes of Khongoryn Els, ride Bactrian camels with herder families, walk the Flaming Cliffs where the first dinosaur eggs were found, and stand inside Erdene Zuu — the monastery built from the stones of the imperial capital.\n\nWe travel by private 4WD with a dedicated guide and driver, sleeping in the best tourist ger camps along the route and a 4-star hotel in Ulaanbaatar. Group sizes stay under sixteen so every camp visit feels personal.",
                'type' => 'join',
                'duration_days' => 14,
                'price_from' => 2596,
                'rating' => 4.9,
                'reviews_count' => 214,
                'image' => '/images/hero-steppe.svg',
                'highlights' => [
                    'Sunset camel trek over the Khongoryn Els singing dunes',
                    'Flaming Cliffs of Bayanzag at golden hour',
                    'Erdene Zuu monastery and the ancient capital Kharkhorin',
                    'A night as guests of a nomadic herder family',
                    'Wild takhi horses in Khustai National Park',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['best-seller', 'cultural-nomadic', 'nature-exploring', 'horse-camel-ride'],
                'destinations' => ['gobi-desert', 'kharkhorin-erdene-zuu', 'khustai', 'ulaanbaatar', 'khorgo-terkhiin-tsagaan'],
                'itinerary' => [
                    ['Arrival in Ulaanbaatar', "You'll be greeted at Chinggis Khaan International Airport and escorted to your 4-star hotel. In the afternoon we visit Gandan Monastery, Sukhbaatar Square and the National Museum, then watch the city glow from Zaisan Hill.", 'L+D', '4* hotel', null],
                    ['Flight south & Yol Valley', 'A morning flight brings us to Dalanzadgad, gateway of the South Gobi. We hike the shaded gorge of Yol Valley in the Gurvan Saikhan mountains, where ice sheets linger into summer.', 'B+L+D', 'Ger camp', '40km drive'],
                    ['Khongoryn Els sand dunes', 'We drive west to the 100 km wall of the singing dunes. In the evening, climb the 300 m crest of Khongor for a sunset you will not forget.', 'B+L+D', 'Ger camp', '200km, 5-6h'],
                    ['Camel trek & herder family', 'Morning camel ride along the dune edge with a local herder family — learn how they milk mares, make aaruul and move camp with the seasons.', 'B+L+D', 'Ger camp', null],
                    ['Flaming Cliffs of Bayanzag', 'Cross the desert steppe to Bayanzag, where Roy Chapman Andrews unearthed the first dinosaur eggs in 1923. Golden-hour walk along the red escarpment.', 'B+L+D', 'Ger camp', '150km, 4h'],
                    ['Ongi Monastery ruins', 'North through the Middle Gobi to the riverside ruins of Ongi, once one of the largest monasteries in Mongolia, destroyed in the purges of 1939.', 'B+L+D', 'Ger camp', '180km, 5h'],
                    ['Kharkhorin — the imperial capital', 'Karakorum was the capital of the Great Mongolian Empire in the 13th century. We visit the Kharkhorin Museum and Erdene Zuu monastery with its 108-stupa wall.', 'B+L+D', 'Ger camp', '220km, 5-6h'],
                    ['Tsenkher hot springs', 'A shorter drive into the forested Khangai foothills. Soak in open-air hot spring pools under larch trees — laundry day and a well-earned rest.', 'B+L+D', 'Ger camp', '130km, 3-4h'],
                    ['Khorgo volcano & Great White Lake', 'Climb the crater rim of Khorgo volcano and picnic on the shore of Terkhiin Tsagaan Nuur, the Great White Lake formed by its lava flows.', 'B+L+D', 'Ger camp', '180km, 5h'],
                    ['A day with the nomads', 'A free day at the lake. Ride horses along the shore, help a herder family with the animals, or simply do absolutely nothing beneath the biggest sky on earth.', 'B+L+D', 'Ger camp', null],
                    ['East to Ugii Lake', 'We retrace the Khangai valleys east to bird-rich Ugii Lake, a favorite of cranes and swans. Fresh fish dinner at camp.', 'B+L+D', 'Ger camp', '250km, 6h'],
                    ['Khustai National Park', 'Home of the takhi, the world\'s only remaining wild horse, reintroduced from European zoos in 1992. Evening game drive to watch the harems come to water.', 'B+L+D', 'Ger camp', '200km, 5h'],
                    ['Return to Ulaanbaatar', 'Back to the capital by early afternoon. Free time for cashmere shopping, then a farewell dinner with a traditional folk performance — throat singing included.', 'B+L+D', '4* hotel', '100km, 2h'],
                    ['Departure', 'Transfer to the airport with memories, photographs and, very possibly, plans to come back.', 'B', null, null],
                ],
                'prices' => [[3, 4, 3344], [5, 8, 3113], [9, 12, 2890], [13, 16, 2596]],
                'departures' => ['2026-09-05', '2026-09-19', '2027-06-06', '2027-06-27', '2027-07-18', '2027-08-08', '2027-08-29', '2027-09-12'],
            ],
            [
                'title' => 'Beauty of Mongolia Tour',
                'slug' => 'beauty-of-mongolia-tour',
                'excerpt' => 'Eleven days through Central Mongolia\'s greatest hits — hot springs, volcano lakes, Kharkhorin and wild horses at an easy, scenic pace.',
                'overview' => "The Beauty of Mongolia is our most balanced itinerary: all the landscapes that make travelers fall in love with this country, without the long desert crossings. From the granite valleys of Terelj to the volcanic shores of the Great White Lake, every day ends in a comfortable ger camp with a view.\n\nThe route is ideal for first-time visitors and photographers — expect wild horses, monastery courtyards, hot-spring evenings and at least one horseback ride across open steppe.",
                'type' => 'join',
                'duration_days' => 11,
                'price_from' => 1930,
                'rating' => 4.9,
                'reviews_count' => 168,
                'image' => '/images/volcano-terkh.svg',
                'highlights' => [
                    'Khorgo volcano crater and the Great White Lake',
                    'Open-air hot springs at Tsenkher',
                    'Horseback riding with a herder family',
                    'Erdene Zuu monastery in Kharkhorin',
                    'Gorkhi-Terelj granite valleys and Turtle Rock',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['best-seller', 'nature-exploring', 'cultural-nomadic', 'family-friendly'],
                'destinations' => ['gorkhi-terelj', 'kharkhorin-erdene-zuu', 'khorgo-terkhiin-tsagaan', 'khustai', 'ulaanbaatar'],
                'itinerary' => [
                    ['Arrival & city highlights', 'Airport welcome, hotel check-in and a relaxed city tour: Gandan Monastery, the National Museum and dinner overlooking Sukhbaatar Square.', 'L+D', '4* hotel', null],
                    ['Gorkhi-Terelj National Park', 'Drive into Terelj\'s granite scenery. Climb to Aryabal meditation temple, scramble over Turtle Rock and meet our first herder family.', 'B+L+D', 'Ger camp', '70km, 1.5h'],
                    ['Khustai National Park', 'Cross the steppe to Khustai for an evening drive among wild takhi horses, marmots and red deer.', 'B+L+D', 'Ger camp', '170km, 4h'],
                    ['Kharkhorin', 'Follow the Orkhon valley to the old imperial capital. Erdene Zuu monastery at sunset is one of Mongolia\'s great sights.', 'B+L+D', 'Ger camp', '210km, 5h'],
                    ['Tsenkher hot springs', 'Short mountain drive to Tsenkher. The afternoon is yours: soak in the thermal pools or walk the forested ridgeline above camp.', 'B+L+D', 'Ger camp', '130km, 3h'],
                    ['Khorgo volcano & White Lake', 'Over the Khangai passes to Terkhiin Tsagaan Nuur. Climb the perfect cinder cone of Khorgo for a crater-rim sunset.', 'B+L+D', 'Ger camp', '180km, 5h'],
                    ['Lakeside free day', 'Ride horses along the lava shore, fish for perch, or visit a yak-herding family for fresh clotted cream with wild berries.', 'B+L+D', 'Ger camp', null],
                    ['Ugii Lake', 'Descend east to shallow, warm Ugii Lake — swimming weather in summer, and a birdwatcher\'s paradise year-round.', 'B+L+D', 'Ger camp', '250km, 6h'],
                    ['Hongor sand & Elsen Tasarkhai', 'Walk the surprise mini-Gobi of Elsen Tasarkhai, a 80 km ribbon of dunes beneath the mountains, with an optional camel ride.', 'B+L+D', 'Ger camp', '120km, 3h'],
                    ['Return to Ulaanbaatar', 'Back to the capital for shopping, the Bogd Khaan winter palace and a farewell folk concert with dinner.', 'B+L+D', '4* hotel', '280km, 6h'],
                    ['Departure', 'Private transfer to the airport for your flight home.', 'B', null, null],
                ],
                'prices' => [[3, 4, 2480], [5, 8, 2270], [9, 12, 2090], [13, 16, 1930]],
                'departures' => ['2026-09-08', '2026-09-22', '2027-06-10', '2027-07-01', '2027-07-22', '2027-08-12', '2027-09-02'],
            ],
            [
                'title' => 'Taste of Mongolia Tour',
                'slug' => 'taste-of-mongolia-tour',
                'excerpt' => 'One unforgettable week: the essential Gobi and Central Mongolia sampler for travelers short on time but not on curiosity.',
                'overview' => "Eight days, three landscapes, zero wasted time. The Taste of Mongolia links the capital, the South Gobi's dunes and cliffs, and the imperial valley of Kharkhorin using one internal flight to skip the longest drives.\n\nIt is the perfect first bite of Mongolia — and most travelers who take it come back hungry for more.",
                'type' => 'join',
                'duration_days' => 8,
                'price_from' => 1228,
                'rating' => 4.8,
                'reviews_count' => 142,
                'image' => '/images/gobi-dunes.svg',
                'highlights' => [
                    'Internal flight over the Gobi to save two days of driving',
                    'Khongoryn Els dunes and a herder-family camel trek',
                    'Flaming Cliffs at sunset',
                    'Kharkhorin and Erdene Zuu monastery',
                    'Farewell folk performance in Ulaanbaatar',
                ],
                'is_featured' => true,
                'is_best_seller' => true,
                'categories' => ['best-seller', 'nature-exploring', 'horse-camel-ride'],
                'destinations' => ['gobi-desert', 'kharkhorin-erdene-zuu', 'ulaanbaatar'],
                'itinerary' => [
                    ['Arrival in Ulaanbaatar', 'Meet your guide at the airport, check into the hotel and spend the afternoon at Gandan Monastery and the National Museum.', 'L+D', '4* hotel', null],
                    ['Fly to the Gobi & Yol Valley', 'Morning flight to Dalanzadgad and straight into the mountains: hike the ice gorge of Yol Valley among bearded vultures.', 'B+L+D', 'Ger camp', '40km'],
                    ['Khongoryn Els', 'Drive along the Gurvan Saikhan range to the singing dunes. Sunset climb to the crest — 40 minutes up, a lifetime of bragging rights.', 'B+L+D', 'Ger camp', '200km, 5h'],
                    ['Camels & Flaming Cliffs', 'Camel trek with a herder family in the morning, then across the steppe to Bayanzag for a golden-hour walk on the Flaming Cliffs.', 'B+L+D', 'Ger camp', '150km, 4h'],
                    ['North to Ongi', 'Leave the desert behind for the Ongi river oasis and its haunting monastery ruins. Evening walk along the canyon rim.', 'B+L+D', 'Ger camp', '180km, 5h'],
                    ['Kharkhorin', 'Reach the Orkhon valley and the old capital. Tour Erdene Zuu\'s temples and the excellent Kharkhorin Museum.', 'B+L+D', 'Ger camp', '220km, 5-6h'],
                    ['Return to Ulaanbaatar', 'One last steppe drive back to the city. Cashmere shopping, farewell dinner and a traditional throat-singing concert.', 'B+L+D', '4* hotel', '370km, 7h'],
                    ['Departure', 'Airport transfer at your flight time.', 'B', null, null],
                ],
                'prices' => [[3, 4, 1590], [5, 8, 1450], [9, 12, 1330], [13, 16, 1228]],
                'departures' => ['2026-09-12', '2027-06-05', '2027-06-26', '2027-07-17', '2027-08-07', '2027-08-28'],
            ],
            [
                'title' => 'Naadam Festival & Gobi Tour',
                'slug' => 'naadam-festival-gobi-tour',
                'excerpt' => 'The "Three Manly Games" in full color — opening ceremony, wrestling finals and horse racing — followed by the best of the South Gobi.',
                'overview' => "Every July, Mongolia stops for Naadam: two days of wrestling, archery and children's horse racing that have been celebrated since the empire. This tour pairs reserved-seat access to the Ulaanbaatar festival with a five-day Gobi circuit, so you get the roar of the stadium and the silence of the dunes in a single week.\n\nNaadam departures sell out earliest of all our trips — book well ahead.",
                'type' => 'join',
                'duration_days' => 8,
                'price_from' => 1896,
                'rating' => 5.0,
                'reviews_count' => 96,
                'image' => '/images/naadam-festival.svg',
                'highlights' => [
                    'Reserved seats at the Naadam opening ceremony',
                    'Wrestling finals and airag-drinking ceremonies',
                    'Horse race finish line on the open steppe',
                    'Khongoryn Els dunes and the Flaming Cliffs',
                    'Yol Valley ice gorge hike',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['naadam-events', 'best-seller', 'cultural-nomadic', 'photo-filming'],
                'destinations' => ['ulaanbaatar', 'gobi-desert'],
                'itinerary' => [
                    ['Arrival & festival eve', 'Arrive into a city dressed for its biggest party. Evening deel-fitting (optional) and briefing on tomorrow\'s ceremony.', 'L+D', '4* hotel', null],
                    ['Naadam opening & wrestling', 'Reserved seats for the spectacular opening ceremony, then an afternoon of first-round wrestling and ankle-bone shooting at the side arenas.', 'B+L+D', '4* hotel', null],
                    ['Horse racing at Khui Doloon Khudag', 'Out to the steppe racecourse where thousands of families camp. Watch child jockeys thunder home from 25 km out, then back for the wrestling finals.', 'B+L+D', '4* hotel', '55km'],
                    ['Fly to the Gobi', 'Morning flight south. Afternoon hike through Yol Valley\'s shaded gorge, home of lammergeiers and, into July, sheets of winter ice.', 'B+L+D', 'Ger camp', '40km'],
                    ['Khongoryn Els', 'Full day at the singing dunes: camel trek with herders in the morning, dune-crest sunset in the evening.', 'B+L+D', 'Ger camp', '200km, 5h'],
                    ['Flaming Cliffs', 'Cross to Bayanzag for dinosaur country — walk the red cliffs where the first nest of dinosaur eggs was found a century ago.', 'B+L+D', 'Ger camp', '150km, 4h'],
                    ['Back to Ulaanbaatar', 'Fly back to the capital for last-minute shopping and a farewell dinner with folk performance.', 'B+L+D', '4* hotel', null],
                    ['Departure', 'Airport transfer at your flight time.', 'B', null, null],
                ],
                'prices' => [[3, 4, 2420], [5, 8, 2210], [9, 12, 2030], [13, 16, 1896]],
                'departures' => ['2027-07-09'],
            ],
            [
                'title' => 'Mongolian Gobi Tour',
                'slug' => 'mongolian-gobi-tour',
                'excerpt' => 'A fast, flight-based private escape to the Gobi\'s three icons: Yol Valley, the singing dunes and the Flaming Cliffs.',
                'overview' => "Four days, three legendary places. Flying both ways, this private itinerary distills the South Gobi into a long weekend: the ice gorge of Yol Valley, the 300-meter dunes of Khongoryn Els and the fossil fields of Bayanzag.\n\nAs with all our private tours, dates are yours to choose and the vehicle, guide and cook travel only with your party.",
                'type' => 'private',
                'duration_days' => 4,
                'price_from' => 1029,
                'rating' => 4.8,
                'reviews_count' => 87,
                'image' => '/images/moto-adventure.svg',
                'highlights' => [
                    'Round-trip internal flights included',
                    'Sunset from the crest of Khongoryn Els',
                    'Camel trek with a herder family',
                    'Flaming Cliffs fossil walk',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['nature-exploring', 'horse-camel-ride', 'photo-filming'],
                'destinations' => ['gobi-desert'],
                'itinerary' => [
                    ['Fly to Dalanzadgad & Yol Valley', 'Early flight south, met by your private crew. Hike Yol Valley\'s narrowing gorge beneath 200 m walls.', 'L+D', 'Ger camp', '40km'],
                    ['Khongoryn Els', 'Cross the desert to the singing dunes. Camel ride in the afternoon; sunset climb up the crest.', 'B+L+D', 'Ger camp', '200km, 5h'],
                    ['Flaming Cliffs', 'East to Bayanzag through saxaul forest. Golden-hour walk along the flaming escarpment.', 'B+L+D', 'Ger camp', '150km, 4h'],
                    ['Fly back to Ulaanbaatar', 'Morning flight back to the capital, where the tour ends with an airport or hotel drop-off.', 'B', null, null],
                ],
                'prices' => [[1, 2, 1590], [3, 4, 1290], [5, 8, 1120], [9, 16, 1029]],
                'departures' => [],
            ],
            [
                'title' => 'Best of Altai Mountain Tour',
                'slug' => 'best-of-altai-mountain-tour',
                'excerpt' => 'Western Mongolia\'s glaciated peaks, Kazakh eagle hunters and the petroglyph valleys of Altai Tavan Bogd National Park.',
                'overview' => "The far west is another country: Kazakh-speaking, snow-capped and fiercely hospitable. Based from Ulgii, we travel into Altai Tavan Bogd National Park to walk beneath the five sacred peaks, visit the UNESCO-listed petroglyphs of Tsagaan Salaa and spend a full day with an eagle-hunting family.\n\nA private trip for travelers who want Mongolia at its wildest.",
                'type' => 'private',
                'duration_days' => 6,
                'price_from' => 1590,
                'rating' => 4.9,
                'reviews_count' => 54,
                'image' => '/images/altai-peaks.svg',
                'highlights' => [
                    'Potanin Glacier viewpoint below Khuiten Peak',
                    'A day with a Kazakh eagle-hunting family',
                    'UNESCO petroglyphs of the Tsagaan Salaa valley',
                    'Ulgii\'s Kazakh bazaar and embroidery workshops',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['trekking-hiking', 'nature-exploring', 'photo-filming', 'cultural-nomadic'],
                'destinations' => ['altai-tavan-bogd'],
                'itinerary' => [
                    ['Fly to Ulgii', 'Cross the country by air to Mongolia\'s westernmost province. Explore the Kazakh bazaar and the excellent local museum.', 'L+D', 'Ger camp', null],
                    ['Into Altai Tavan Bogd', 'A spectacular 4WD day over passes and river fords to the national park base camp beneath the five holy peaks.', 'B+L+D', 'Camping / ger', '180km, 6-7h'],
                    ['Potanin Glacier hike', 'Full-day hike to the Potanin Glacier viewpoint (3,100 m) facing Khuiten, Mongolia\'s highest summit.', 'B+L+D', 'Camping / ger', '14km on foot'],
                    ['Petroglyphs of Tsagaan Salaa', 'Descend the valley to one of the world\'s densest rock-art galleries: 10,000 carvings spanning 12,000 years.', 'B+L+D', 'Ger camp', '120km, 4h'],
                    ['Eagle hunter family', 'Spend the day with a Kazakh berkutchi: hold a trained golden eagle, share besbarmak and learn the winter hunting tradition.', 'B+L+D', 'Family ger', '90km, 3h'],
                    ['Fly back to Ulaanbaatar', 'Morning flight east; the trip ends with your hotel or airport transfer.', 'B', null, null],
                ],
                'prices' => [[1, 2, 2290], [3, 4, 1890], [5, 8, 1690], [9, 16, 1590]],
                'departures' => [],
            ],
            [
                'title' => 'Central Mongolia Highlights Tour',
                'slug' => 'central-mongolia-highlights-tour',
                'excerpt' => 'Six easy days linking Khustai\'s wild horses, the mini-Gobi dunes, Kharkhorin and Terelj — Mongolia\'s essential circuit.',
                'overview' => "If you have less than a week, this private loop shows you an astonishing amount of country without a single flight or exhausting drive. Wild horses at dusk, a camel ride at Elsen Tasarkhai, monastery mornings at Erdene Zuu and a final night among Terelj's granite towers.",
                'type' => 'private',
                'duration_days' => 6,
                'price_from' => 1071,
                'rating' => 4.8,
                'reviews_count' => 76,
                'image' => '/images/khustai-horses.svg',
                'highlights' => [
                    'Takhi wild horses at Khustai National Park',
                    'Camel ride on the Elsen Tasarkhai dunes',
                    'Erdene Zuu monastery in Kharkhorin',
                    'Turtle Rock and Aryabal temple in Terelj',
                ],
                'is_featured' => false,
                'is_best_seller' => true,
                'categories' => ['best-seller', 'nature-exploring', 'family-friendly'],
                'destinations' => ['khustai', 'kharkhorin-erdene-zuu', 'gorkhi-terelj', 'chinggis-khaan-statue'],
                'itinerary' => [
                    ['Ulaanbaatar to Khustai', 'Pick-up from your hotel and an easy drive to Khustai National Park. Evening wildlife drive among the takhi.', 'L+D', 'Ger camp', '100km, 2h'],
                    ['Elsen Tasarkhai dunes', 'Continue west to the "mini-Gobi" — 80 km of dunes below the Khugnu Khan mountains. Camel ride and dune picnic.', 'B+L+D', 'Ger camp', '180km, 4h'],
                    ['Kharkhorin', 'Morning at Erdene Zuu monastery and the Kharkhorin museum; afternoon walk to the phallic rock and turtle stones of the old capital.', 'B+L+D', 'Ger camp', '80km, 2h'],
                    ['Orkhon valley herders', 'A day in the UNESCO-listed Orkhon valley: visit a horse-breeding family, try airag in season, and ride to a small waterfall.', 'B+L+D', 'Ger camp', '60km, 2h'],
                    ['Across to Terelj', 'A longer scenic drive east through Ulaanbaatar to Gorkhi-Terelj. Sunset scramble on Turtle Rock.', 'B+L+D', 'Ger camp', '420km, 7h'],
                    ['Chinggis statue & return', 'Climb the 40 m stainless statue of Chinggis Khaan at Tsonjin Boldog, then return to Ulaanbaatar by early afternoon.', 'B+L', null, '90km, 2h'],
                ],
                'prices' => [[1, 2, 1560], [3, 4, 1290], [5, 8, 1150], [9, 16, 1071]],
                'departures' => [],
            ],
            [
                'title' => 'Kharkhorin & South Gobi Tour',
                'slug' => 'kharkhorin-south-gobi-tour',
                'excerpt' => 'Desert and empire in one week: overland from the dunes and cliffs of the Gobi to the monastery courtyards of the old capital.',
                'overview' => "This private route joins Mongolia's two most storied landscapes overland, the way caravans once did. South through dinosaur country to the great dunes, then north across steppe to Kharkhorin, with herder-family visits threaded along the whole route.",
                'type' => 'private',
                'duration_days' => 7,
                'price_from' => 1468,
                'rating' => 4.7,
                'reviews_count' => 63,
                'image' => '/images/kharkhorin.svg',
                'highlights' => [
                    'Tsagaan Suvarga\'s painted badlands',
                    'Yol Valley, Khongoryn Els and the Flaming Cliffs',
                    'Ongi monastery ruins at sunset',
                    'Erdene Zuu monastery in Kharkhorin',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['nature-exploring', 'cultural-nomadic'],
                'destinations' => ['gobi-desert', 'kharkhorin-erdene-zuu'],
                'itinerary' => [
                    ['South to Tsagaan Suvarga', 'Leave the capital for the painted clay cliffs of Tsagaan Suvarga, glowing pink and white at sunset.', 'L+D', 'Ger camp', '420km, 7h'],
                    ['Yol Valley', 'Into the Gurvan Saikhan mountains for the classic gorge hike among ibex and vultures.', 'B+L+D', 'Ger camp', '220km, 5h'],
                    ['Khongoryn Els', 'West along the range to the singing dunes; sunset climb and, if you like, a starlit dune picnic.', 'B+L+D', 'Ger camp', '200km, 5h'],
                    ['Camels & Flaming Cliffs', 'Camel trek in the morning, Flaming Cliffs in the golden evening light.', 'B+L+D', 'Ger camp', '150km, 4h'],
                    ['Ongi Monastery', 'North to the Ongi river ruins. Evening tea with the resident monk in the small rebuilt temple.', 'B+L+D', 'Ger camp', '180km, 5h'],
                    ['Kharkhorin', 'The old imperial capital: Erdene Zuu, the museum and the Orkhon valley overlook.', 'B+L+D', 'Ger camp', '220km, 5-6h'],
                    ['Return to Ulaanbaatar', 'Steppe highway home, arriving late afternoon with a drop-off at your hotel.', 'B+L', null, '370km, 7h'],
                ],
                'prices' => [[1, 2, 1980], [3, 4, 1690], [5, 8, 1540], [9, 16, 1468]],
                'departures' => [],
            ],
            [
                'title' => 'Horseback Adventure in Khustai',
                'slug' => 'horseback-adventure-khustai',
                'excerpt' => 'A two-day riding escape among the wild horses — the perfect add-on to any Mongolia itinerary.',
                'overview' => "Learn to ride Mongolian-style on gentle local horses, camp beside Khustai National Park and watch the wild takhi come down to the river at dusk. Short, sweet, and consistently the most re-booked trip we run.",
                'type' => 'private',
                'duration_days' => 2,
                'price_from' => 243,
                'rating' => 4.9,
                'reviews_count' => 121,
                'image' => '/images/horse-trek.svg',
                'highlights' => [
                    'Half-day guided ride with a herder wrangler',
                    'Evening takhi-watching drive',
                    'Night in a family-run ger camp',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['horse-camel-ride', 'family-friendly', 'nature-exploring'],
                'destinations' => ['khustai'],
                'itinerary' => [
                    ['Ride the buffer zone', 'Morning pick-up, riding briefing and a 3-4 hour ride through the hills bordering the park. Evening wildlife drive to see the takhi.', 'L+D', 'Ger camp', '100km, 2h'],
                    ['Morning ride & return', 'Sunrise ride along the Tuul river, lunch with the herder family, and back in Ulaanbaatar by mid-afternoon.', 'B+L', null, '100km, 2h'],
                ],
                'prices' => [[1, 2, 385], [3, 4, 310], [5, 8, 268], [9, 16, 243]],
                'departures' => [],
            ],
            [
                'title' => 'Lake Khuvsgul Tour',
                'slug' => 'lake-khuvsgul-tour',
                'excerpt' => 'Four days on the "Blue Pearl" — alpine water, larch forest, reindeer culture and horseback trails along the shore.',
                'overview' => "Khuvsgul holds nearly seventy percent of Mongolia's fresh water in a single alpine trench of impossible blue. We fly to Murun and spend three nights on the western shore: kayaking, riding, visiting Tsaatan reindeer herders in their autumn camp and eating just-caught fish by the fire.",
                'type' => 'private',
                'duration_days' => 4,
                'price_from' => 1090,
                'rating' => 4.8,
                'reviews_count' => 92,
                'image' => '/images/lake-khuvsgul.svg',
                'highlights' => [
                    'Flights to Murun included',
                    'Kayak or boat trip on the lake',
                    'Visit a Tsaatan reindeer family (seasonal)',
                    'Shoreline horseback ride through larch forest',
                ],
                'is_featured' => true,
                'is_best_seller' => false,
                'categories' => ['nature-exploring', 'fishing-rafting', 'family-friendly'],
                'destinations' => ['lake-khuvsgul'],
                'itinerary' => [
                    ['Fly to Murun & the lake', 'Morning flight north, then a scenic drive to the lakeshore at Khatgal. Afternoon walk to the Ongolig viewpoint.', 'L+D', 'Ger camp', '100km, 2h'],
                    ['On the water', 'Kayak the glass-clear shallows or take the camp boat to Wish Island. Evening bonfire with fresh grayling.', 'B+L+D', 'Ger camp', null],
                    ['Horses & reindeer', 'Morning horseback ride through the larch forest; afternoon visit to a Tsaatan reindeer family in their seasonal camp.', 'B+L+D', 'Ger camp', '30km'],
                    ['Return flight', 'Drive back to Murun for the afternoon flight to Ulaanbaatar.', 'B+L', null, '100km, 2h'],
                ],
                'prices' => [[1, 2, 1560], [3, 4, 1290], [5, 8, 1160], [9, 16, 1090]],
                'departures' => [],
            ],
            [
                'title' => 'Motorcycle Adventure Tour',
                'slug' => 'motorcycle-adventure-tour',
                'excerpt' => 'Seven days of open-throttle steppe on well-prepped enduro bikes, with a full support truck, mechanic and camp crew.',
                'overview' => "Mongolia may be the last great motorcycle country: a thousand kilometers of open track, river crossings, dune skirting and not a fence in sight. Riding Japanese 450cc enduros with a support 4WD carrying luggage, spares and a cook, this loop links Khustai, the Orkhon valley and Elsen Tasarkhai.\n\nFor confident off-road riders; an international license with motorcycle category is required.",
                'type' => 'private',
                'duration_days' => 7,
                'price_from' => 2835,
                'rating' => 4.9,
                'reviews_count' => 41,
                'image' => '/images/moto-adventure.svg',
                'highlights' => [
                    'Well-maintained 450cc enduro fleet',
                    'Full support: 4WD truck, mechanic, cook',
                    'River crossings in the Orkhon valley',
                    'Dune riding at Elsen Tasarkhai',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['motorcycle-bike', 'nature-exploring'],
                'destinations' => ['khustai', 'kharkhorin-erdene-zuu', 'khorgo-terkhiin-tsagaan'],
                'itinerary' => [
                    ['Fitting & shakedown ride', 'Bike fitting, paperwork and a 60 km shakedown loop outside Ulaanbaatar to tune suspension and habits.', 'L+D', 'Ger camp', '60km ride'],
                    ['To Khustai', 'First real stage over open steppe tracks to Khustai; evening ride to the takhi viewing valley.', 'B+L+D', 'Ger camp', '140km ride'],
                    ['Elsen Tasarkhai', 'Sand skills day: skirting the mini-Gobi dunes, then camp beneath Khugnu Khan mountain.', 'B+L+D', 'Ger camp', '180km ride'],
                    ['Kharkhorin & Orkhon', 'Cross to the Orkhon valley with its first river fords. Afternoon at Erdene Zuu monastery — boots off at the gate.', 'B+L+D', 'Ger camp', '160km ride'],
                    ['Orkhon waterfall', 'The best riding day: lava-field tracks and multiple crossings up-valley to Ulaan Tsutgalan waterfall.', 'B+L+D', 'Ger camp', '170km ride'],
                    ['Long steppe stage', 'A glorious 300 km run east on fast gravel and grass, camping at Ugii Lake for a swim and a fish dinner.', 'B+L+D', 'Ger camp', '300km ride'],
                    ['Return to Ulaanbaatar', 'Final stage back to the city, bikes returned by mid-afternoon with a farewell team dinner.', 'B+L+D', null, '190km ride'],
                ],
                'prices' => [[1, 2, 3480], [3, 4, 3120], [5, 8, 2960], [9, 12, 2835]],
                'departures' => [],
            ],
            [
                'title' => 'Experiencing Nomadic Life Tour',
                'slug' => 'experiencing-nomadic-life-tour',
                'excerpt' => 'Eight slow days living with two herder families — milk the yaks, ride with the herd, make dinner in the ger and let the steppe set the pace.',
                'overview' => "This is not sightseeing; it is a homestay on the grandest scale. We place you with families we have worked beside for decades — one horse-breeding family in the Orkhon valley, one yak-herding family in the Khangai foothills. You will help with the animals, learn to make buuz and byaslag cheese, ride out with the herd and sleep in your own guest ger.\n\nExpect few showers, endless tea, and the kind of welcome that rearranges what you thought hospitality meant.",
                'type' => 'join',
                'duration_days' => 8,
                'price_from' => 1235,
                'rating' => 4.9,
                'reviews_count' => 78,
                'image' => '/images/nomad-life.svg',
                'highlights' => [
                    'Two multi-night herder family homestays',
                    'Daily herding, milking and dairy-making',
                    'Horseback riding with the family herd',
                    'Traditional cooking: buuz, khorkhog, byaslag',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['cultural-nomadic', 'horse-camel-ride', 'photo-filming'],
                'destinations' => ['kharkhorin-erdene-zuu', 'khorgo-terkhiin-tsagaan'],
                'itinerary' => [
                    ['To the Orkhon valley', 'Drive west into the UNESCO-listed valley and settle in with your first host family before evening milking.', 'L+D', 'Family guest ger', '360km, 7h'],
                    ['The rhythm of the herd', 'Morning milking, then ride out with the horses. Afternoon lesson in airag — fermented mare\'s milk, the national drink.', 'B+L+D', 'Family guest ger', null],
                    ['Moving with the animals', 'Help the family shift the sheep flock to fresh pasture; picnic lunch in the saddle; evening dung-collecting (yes, really — it is the fuel).', 'B+L+D', 'Family guest ger', null],
                    ['Across the Khangai', 'Farewell to family one and a beautiful pass-crossing drive to the yak herders in the high foothills.', 'B+L+D', 'Family guest ger', '160km, 4h'],
                    ['Yak day', 'Yaks are comedy and cashmere in one animal. Combing, milking and an afternoon making byaslag cheese and clotted cream.', 'B+L+D', 'Family guest ger', null],
                    ['Khorkhog feast', 'Ride to the neighbors\' camp to help prepare khorkhog — mutton barbecued with hot river stones — for a shared evening feast.', 'B+L+D', 'Family guest ger', null],
                    ['Kharkhorin', 'Break the journey home at the old capital for Erdene Zuu monastery and a real shower at a tourist camp.', 'B+L+D', 'Ger camp', '140km, 3h'],
                    ['Return to Ulaanbaatar', 'Home to the capital by late afternoon, changed in ways that take a while to name.', 'B+L', null, '370km, 7h'],
                ],
                'prices' => [[3, 4, 1620], [5, 8, 1440], [9, 12, 1320], [13, 16, 1235]],
                'departures' => ['2026-09-10', '2027-06-15', '2027-07-13', '2027-08-10', '2027-09-07'],
            ],
            [
                'title' => 'Eagle Hunters & Winter Steppe Tour',
                'slug' => 'eagle-hunters-winter-tour',
                'excerpt' => 'Five crisp days in the white season: eagle hunting on horseback, frozen rivers, and gers glowing warm against the snow.',
                'overview' => "Winter is Mongolia's secret season — luminous, silent and utterly photogenic. Based in the west near Ulgii, we join Kazakh berkutchi as they fly golden eagles from the ridgelines, ride through snow-dusted valleys and thaw out each night by the stove with endless milk tea.\n\nDaytime temperatures run -10 to -20°C; we provide expedition-grade sleeping bags and the gers are kept toasty.",
                'type' => 'private',
                'duration_days' => 5,
                'price_from' => 980,
                'rating' => 4.9,
                'reviews_count' => 37,
                'image' => '/images/eagle-hunter.svg',
                'highlights' => [
                    'Ride out with eagle hunters on winter hunts',
                    'Portrait sessions in golden winter light',
                    'Kazakh homestay with traditional meals',
                    'Frozen river walks and ice formations',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['winter', 'photo-filming', 'cultural-nomadic'],
                'destinations' => ['altai-tavan-bogd'],
                'itinerary' => [
                    ['Fly to Ulgii', 'Arrive in the frozen west and settle in with our host family; evening briefing on winter riding and layering.', 'L+D', 'Kazakh homestay', null],
                    ['First hunt', 'Ride the ridgelines with two berkutchi and their eagles as they scan the valleys for fox and hare.', 'B+L+D', 'Kazakh homestay', '20km ride'],
                    ['Deep valley day', 'Horse-sledge along a frozen river into a side valley for ice formations and winter portraits at golden hour.', 'B+L+D', 'Kazakh homestay', null],
                    ['Eagle culture', 'Morning hunt, afternoon learning the training of young eagles — hooding, calling and the bond that lasts a decade.', 'B+L+D', 'Kazakh homestay', '15km ride'],
                    ['Return flight', 'Farewell besbarmak lunch and the afternoon flight back to Ulaanbaatar.', 'B+L', null, null],
                ],
                'prices' => [[1, 2, 1420], [3, 4, 1180], [5, 8, 1050], [9, 12, 980]],
                'departures' => [],
            ],
            [
                'title' => 'Terelj National Park Day Trip',
                'slug' => 'terelj-day-trip',
                'excerpt' => 'The classic single-day escape: Chinggis Khaan statue, Turtle Rock, Aryabal temple and lunch with a herder family.',
                'overview' => "Only have a day between flights? This is the one. An early start takes you to the 40-meter Chinggis Khaan equestrian statue, then into Gorkhi-Terelj's granite scenery for Turtle Rock, the ridge-top Aryabal meditation temple and a home-cooked lunch in a real family ger.",
                'type' => 'private',
                'duration_days' => 1,
                'price_from' => 95,
                'rating' => 4.7,
                'reviews_count' => 156,
                'image' => '/images/terelj-park.svg',
                'highlights' => [
                    'Chinggis Khaan statue complex',
                    'Turtle Rock and Aryabal temple',
                    'Home-cooked lunch with a herder family',
                    'Optional short horseback ride',
                ],
                'is_featured' => false,
                'is_best_seller' => false,
                'categories' => ['family-friendly', 'nature-exploring'],
                'destinations' => ['gorkhi-terelj', 'chinggis-khaan-statue'],
                'itinerary' => [
                    ['Terelj in a day', 'Depart 08:00; climb the Chinggis statue, hike to Aryabal temple, scramble Turtle Rock, and share lunch in a family ger before returning by 18:00.', 'L', null, '160km round trip'],
                ],
                'prices' => [[1, 2, 165], [3, 4, 125], [5, 8, 105], [9, 16, 95]],
                'departures' => [],
            ],
        ];
    }
}
